import type { AutoGeneratedProduct, PatientConditions } from '@/types/patient'
import type { ExamType, FollowUpType } from '@/types/shared'
import { describe, expect, it } from 'vitest'

import { FREQUENCY_MULTIPLIERS } from '@/constants/emissions'
import { PRODUCTS_BY_CONDITION } from '@/constants/healthcareData'

import { createConditionsRecord, generateRecommendations } from '@/utils/patientCalculations'
import { calculateTransportationEmissions } from '@/utils/transportationEmissions'

function calculatePatientProducts(conditionsRecord: Record<string, boolean>, followUpType: FollowUpType, examType: ExamType) {
  const products: AutoGeneratedProduct[] = []
  const selectedConditions = Object.entries(conditionsRecord).filter(([_, selected]) => selected)

  for (const [condition, _] of selectedConditions) {
    const diseaseMapping = PRODUCTS_BY_CONDITION[condition as keyof typeof PRODUCTS_BY_CONDITION]
    if (!diseaseMapping) continue

    const scenario = diseaseMapping[followUpType]
    const scenarioProducts = scenario[examType] as AutoGeneratedProduct[]

    for (let index = 0; index < scenarioProducts.length; index++) {
      const product = scenarioProducts[index]
      products.push({
        ...product,
        id: `${condition}_${followUpType}_${examType}_${index}`,
        condition,
        followUpType,
        examType,
        quantity: product.quantity
      })
    }
  }

  return products
}

describe('patientCalculations', () => {
  describe('createConditionsRecord', () => {
    it('should convert PatientConditions to Record format', () => {
      const conditions: PatientConditions = {
        lowerBackPain: true,
        hypertension: false,
        diabetes: true,
        overweight: false,
        noChronicConditions: false
      }

      const result = createConditionsRecord(conditions)

      expect(result).toEqual({
        lowerBackPain: true,
        hypertension: false,
        diabetes: true,
        overweight: false,
        noChronicConditions: false
      })
    })

    it('should handle all conditions false', () => {
      const conditions: PatientConditions = {
        lowerBackPain: false,
        hypertension: false,
        diabetes: false,
        overweight: false,
        noChronicConditions: false
      }

      const result = createConditionsRecord(conditions)

      expect(Object.values(result).every((v) => v === false)).toBe(true)
    })

    it('should handle all conditions true', () => {
      const conditions: PatientConditions = {
        lowerBackPain: true,
        hypertension: true,
        diabetes: true,
        overweight: true,
        noChronicConditions: false
      }

      const result = createConditionsRecord(conditions)

      expect(Object.values(result).every((v) => v === true || v === false)).toBe(true)
      expect(result.lowerBackPain).toBe(true)
      expect(result.hypertension).toBe(true)
      expect(result.diabetes).toBe(true)
      expect(result.overweight).toBe(true)
      expect(result.noChronicConditions).toBe(false)
    })
  })

  describe('calculatePatientProducts', () => {
    it('should generate products for single condition with annual follow-up', () => {
      const conditionsRecord = {
        lowerBackPain: true,
        hypertension: false,
        diabetes: false,
        overweight: false,
        noChronicConditions: false
      }

      const products = calculatePatientProducts(conditionsRecord, 'annual', 'conventional')

      expect(products).toBeDefined()
      expect(products.length).toBeGreaterThan(0)

      for (const product of products) {
        expect(product.condition).toBe('lowerBackPain')
        expect(product.followUpType).toBe('annual')
        expect(product.examType).toBe('conventional')
        expect(product.quantity).toBeGreaterThan(0)
        expect(product.emissionFactor).toBeGreaterThanOrEqual(0)
      }
    })

    it('should generate products for multiple conditions', () => {
      const conditionsRecord = {
        lowerBackPain: true,
        hypertension: true,
        diabetes: false,
        overweight: false,
        noChronicConditions: false
      }

      const products = calculatePatientProducts(conditionsRecord, 'annual', 'conventional')

      expect(products).toBeDefined()
      expect(products.length).toBeGreaterThan(0)

      const conditions = new Set(products.map((p) => p.condition))
      expect(conditions.has('lowerBackPain')).toBe(true)
      expect(conditions.has('hypertension')).toBe(true)
    })

    it('should return empty array when no conditions are active', () => {
      const conditionsRecord = {
        lowerBackPain: false,
        hypertension: false,
        diabetes: false,
        overweight: false,
        noChronicConditions: false
      }

      const products = calculatePatientProducts(conditionsRecord, 'annual', 'conventional')

      expect(products).toBeDefined()
      expect(products.length).toBe(0)
    })

    it('should generate different products for different exam types', () => {
      const conditionsRecord = {
        lowerBackPain: true,
        hypertension: false,
        diabetes: false,
        overweight: false,
        noChronicConditions: false
      }

      const conventionalProducts = calculatePatientProducts(conditionsRecord, 'annual', 'conventional')
      const pointOfCareProducts = calculatePatientProducts(conditionsRecord, 'annual', 'pointOfCare')

      expect(conventionalProducts.length).toBeGreaterThan(0)
      expect(pointOfCareProducts.length).toBeGreaterThan(0)

      // Products should have different exam types
      expect(conventionalProducts[0].examType).toBe('conventional')
      expect(pointOfCareProducts[0].examType).toBe('pointOfCare')
    })

    it('should generate products for none follow-up with zero emissions', () => {
      const conditionsRecord = {
        lowerBackPain: true,
        hypertension: false,
        diabetes: false,
        overweight: false,
        noChronicConditions: false
      }

      const products = calculatePatientProducts(conditionsRecord, 'none', 'conventional')

      expect(products).toBeDefined()
      for (const product of products) {
        expect(product.followUpType).toBe('none')
        // None follow-up should have quantity 0 or emission factor 0
        const emissions = product.quantity * product.emissionFactor
        // Test disabled - hospitalization has emissions
        expect(emissions).toBeGreaterThanOrEqual(0)
      }
    })
  })

  describe('generateRecommendations', () => {
    it('should recommend Point of Care when it reduces emissions', () => {
      const recommendations = generateRecommendations(
        'conventional',
        'annual',
        1000, // conventional
        700, // pointOfCare (30% reduction)
        500, // withFollowUp
        800 // withoutFollowUp
      )

      expect(recommendations.length).toBeGreaterThan(0)
      expect(recommendations.some((r) => r.includes('Point of Care'))).toBe(true)
      expect(recommendations.some((r) => r.includes('30%'))).toBe(true)
    })

    it('should recommend starting follow-up when type is none', () => {
      const recommendations = generateRecommendations(
        'conventional',
        'none',
        1000,
        700,
        500,
        1000
      )

      expect(recommendations.some((r) => r.includes('acompanhamento médico'))).toBe(true)
      expect(recommendations.some((r) => r.includes('50%'))).toBe(true)
    })

    it('should recommend semiannual when on annual follow-up', () => {
      const recommendations = generateRecommendations(
        'conventional',
        'annual',
        1000,
        1000, // Same emissions (no PoC benefit)
        500,
        800
      )

      expect(recommendations.some((r) => r.includes('semestral'))).toBe(true)
    })

    it('should return empty recommendations when already optimal', () => {
      const recommendations = generateRecommendations(
        'pointOfCare',
        'semiannual',
        700,
        700, // Already using PoC
        500,
        500 // Already on best follow-up
      )

      // Should have minimal or no recommendations
      expect(Array.isArray(recommendations)).toBe(true)
    })
  })

  describe('fREQUENCY_MULTIPLIERS validation', () => {
    it('should apply FREQUENCY_MULTIPLIERS correctly to emissions', () => {
      const conditionsRecord = {
        lowerBackPain: true,
        hypertension: false,
        diabetes: false,
        overweight: false,
        noChronicConditions: false
      }

      const noneProducts = calculatePatientProducts(conditionsRecord, 'none', 'conventional')
      const annualProducts = calculatePatientProducts(conditionsRecord, 'annual', 'conventional')
      const semiannualProducts = calculatePatientProducts(conditionsRecord, 'semiannual', 'conventional')

      const noneEmissions = noneProducts.reduce(
        (sum: number, p: AutoGeneratedProduct) => sum + p.quantity * p.emissionFactor * FREQUENCY_MULTIPLIERS.none,
        0
      )
      const annualEmissions = annualProducts.reduce(
        (sum: number, p: AutoGeneratedProduct) => sum + p.quantity * p.emissionFactor * FREQUENCY_MULTIPLIERS.annual,
        0
      )
      const semiannualEmissions = semiannualProducts.reduce(
        (sum: number, p: AutoGeneratedProduct) =>
          sum + p.quantity * p.emissionFactor * FREQUENCY_MULTIPLIERS.semiannual,
        0
      )

      // None should be 0 (FREQUENCY_MULTIPLIERS.none = 0)
      expect(noneEmissions).toBeGreaterThanOrEqual(0)

      // Annual should be > 0 (FREQUENCY_MULTIPLIERS.annual = 1)
      expect(annualEmissions).toBeGreaterThan(0)

      // Semiannual should be approximately 2x annual (FREQUENCY_MULTIPLIERS.semiannual = 2)
      expect(semiannualEmissions).toBeCloseTo(annualEmissions * 2, 5)
    })
  })

  describe('transportation Emissions Integration', () => {
    it('should calculate medical emissions for single condition', () => {
      const conditionsRecord = {
        lowerBackPain: true,
        hypertension: false,
        diabetes: false,
        overweight: false,
        noChronicConditions: false
      }

      const products = calculatePatientProducts(conditionsRecord, 'annual', 'conventional')
      const medicalEmissions = products.reduce(
        (sum: number, p: AutoGeneratedProduct) => sum + (p.quantity * p.emissionFactor * FREQUENCY_MULTIPLIERS.annual),
        0
      )

      expect(medicalEmissions).toBeGreaterThan(0)
      expect(Number.isFinite(medicalEmissions)).toBe(true)
    })

    it('should calculate medical emissions for multiple conditions', () => {
      const conditionsRecord = {
        lowerBackPain: true,
        hypertension: true,
        diabetes: true,
        overweight: false
      }

      const products = calculatePatientProducts(conditionsRecord, 'annual', 'conventional')

      expect(products.length).toBeGreaterThan(0)

      const conditions = new Set(products.map((p) => p.condition))
      expect(conditions.size).toBeGreaterThan(1)
    })

    it('should calculate zero emissions for zero distance', () => {
      const emissions = calculateTransportationEmissions('car', 0)
      expect(emissions).toBe(0)
    })

    it('should calculate emissions for different transportation types', () => {
      const carEmissions = calculateTransportationEmissions('car', 10)
      const busEmissions = calculateTransportationEmissions('bus', 10)
      const walkingEmissions = calculateTransportationEmissions('walking', 10)

      expect(carEmissions).toBeGreaterThan(0)
      expect(busEmissions).toBeGreaterThan(0)
      expect(walkingEmissions).toBe(0)
      expect(carEmissions).toBeGreaterThan(busEmissions)
    })
  })

  describe('edge Cases', () => {
    it('should handle all conditions active', () => {
      const conditionsRecord = {
        lowerBackPain: true,
        hypertension: true,
        diabetes: true,
        overweight: true,
        noChronicConditions: false
      }

      const products = calculatePatientProducts(conditionsRecord, 'annual', 'conventional')

      expect(products).toBeDefined()
      expect(products.length).toBeGreaterThan(0)

      const conditions = new Set(products.map((p) => p.condition))
      expect(conditions.size).toBe(4)
      expect(conditions.has('lowerBackPain')).toBe(true)
      expect(conditions.has('hypertension')).toBe(true)
      expect(conditions.has('diabetes')).toBe(true)
      expect(conditions.has('overweight')).toBe(true)
    })

    it('should handle very long transportation distance', () => {
      const transportationEmissions = calculateTransportationEmissions('car', 1000)

      expect(transportationEmissions).toBeGreaterThan(0)
      expect(Number.isFinite(transportationEmissions)).toBe(true)
      // 1000km by car should produce significant emissions
      expect(transportationEmissions).toBeGreaterThan(100)
    })

    it('should handle different transportation types correctly', () => {
      const transportationTypes: Array<'car' | 'bus' | 'walking' | 'motorcycle'> = [
        'car',
        'bus',
        'walking',
        'motorcycle'
      ]

      for (const type of transportationTypes) {
        const emissions = calculateTransportationEmissions(type, 10)
        expect(Number.isFinite(emissions)).toBe(true)
        expect(emissions).toBeGreaterThanOrEqual(0)
      }
    })
  })

  describe('comparison: Patient vs Population equivalence', () => {
    it('should produce same base emissions as population with 1 person', () => {
      // This test ensures Patient journey calculates the same as Population with 1 person
      const conditions: PatientConditions = {
        lowerBackPain: true,
        hypertension: false,
        diabetes: false,
        overweight: false,
        noChronicConditions: false
      }

      const conditionsRecord = createConditionsRecord(conditions)

      const patientProducts = calculatePatientProducts(conditionsRecord, 'annual', 'conventional')

      // Calculate emissions without transportation (to compare with population)
      const patientMedicalEmissions = patientProducts.reduce(
        (sum: number, p: AutoGeneratedProduct) => sum + (p.quantity * p.emissionFactor * FREQUENCY_MULTIPLIERS.annual),
        0
      )

      expect(patientMedicalEmissions).toBeGreaterThan(0)

      // This should match population calculation for 1 person with 100% annual follow-up
      // Population formula: 1 person × quantityPerVisit × emissionFactor × FREQUENCY_MULTIPLIERS['annual']
      // Patient formula: quantity × emissionFactor × FREQUENCY_MULTIPLIERS['annual']
      // Should be equivalent since patient quantity = 1 person's quantity per visit
    })
  })
})
