CREATE TABLE IF NOT EXISTS "Anamnesis" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    age INTEGER NOT NULL CHECK (age >= 0 AND age <= 120),
    gender VARCHAR(20) NOT NULL CHECK (gender IN ('feminino', 'masculino', 'outro')),
    walk_days INTEGER NOT NULL CHECK (walk_days >= 0 AND walk_days <= 7),
    walk_minutes INTEGER NOT NULL CHECK (walk_minutes >= 0 AND walk_minutes <= 1440),
    mod_days INTEGER NOT NULL CHECK (mod_days >= 0 AND mod_days <= 7),
    mod_minutes INTEGER NOT NULL CHECK (mod_minutes >= 0 AND mod_minutes <= 1440),
    vig_days INTEGER NOT NULL CHECK (vig_days >= 0 AND vig_days <= 7),
    vig_minutes INTEGER NOT NULL CHECK (vig_minutes >= 0 AND vig_minutes <= 1440),
    veg_portions INTEGER NOT NULL CHECK (veg_portions >= 0 AND veg_portions <= 6),
    fruit_portions INTEGER NOT NULL CHECK (fruit_portions >= 0 AND fruit_portions <= 6),
    ultra_processed INTEGER NOT NULL CHECK (ultra_processed >= 0 AND ultra_processed <= 6),
    chronic_dx TEXT[] NOT NULL DEFAULT '{}',
    smoke_status VARCHAR(50) NOT NULL,
    alcohol_days_week INTEGER NOT NULL CHECK (alcohol_days_week >= 0 AND alcohol_days_week <= 7),
    alcohol_drinks_day INTEGER NOT NULL CHECK (alcohol_drinks_day >= 0 AND alcohol_drinks_day <= 7),
    followup VARCHAR(50) NOT NULL,
    blood_tests_year INTEGER NOT NULL CHECK (blood_tests_year >= 0 AND blood_tests_year <= 12),
    lab_type VARCHAR(50),
    hipertensao JSONB,
    diabetes JSONB,
    sobrepeso JSONB,
    lombalgia JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
