import type React from 'react'
import type { ElementPropsWithElementRef, ScrollState } from 'react-scrollbars-custom/dist/types/types'
import type { AutoGeneratedProduct } from '@/types/patient'
import type { ExamType, FollowUpType } from '@/types/shared'
import { useEffect, useMemo } from 'react'
import { Scrollbar } from 'react-scrollbars-custom'
import { getFollowUpConfig, getProductName, PRODUCTS_BY_CONDITION } from '@/constants/healthcareData'
import useLanguage from '@/hooks/useLanguage'
import { usePatient } from '@/hooks/usePatient'

type ScrollbarElementProps = ElementPropsWithElementRef<HTMLDivElement>

export function PatientStep4() {
  const { data, updateExamData, getConditionsTitle } = usePatient()
  const { t, language } = useLanguage()

  // Obter configuração de follow-up traduzida
  const followUpConfig = useMemo(() => getFollowUpConfig(language), [language])

  const SHOW_FINAL_QUANTITY_COLUMN = false

  const handleExamTypeChange = (type: ExamType) => {
    updateExamData({
      ...data.examData,
      type
    })
  }

  // Usar produtos e configurações centralizados
  const productsByCondition = PRODUCTS_BY_CONDITION

  interface ProductsByScenario {
    conventional?: Array<{
      name: string
      category: string
      emissionFactor: number
      quantity: number
    }>
    pointOfCare?: Array<{
      name: string
      category: string
      emissionFactor: number
      quantity: number
    }>
  }

  type ConditionProducts = Record<string, ProductsByScenario>

  /**
   * Adiciona produtos de um tipo específico (conventional ou pointOfCare) ao array de produtos
   * @param products - Array onde os produtos serão adicionados
   * @param conditionProducts - Objeto contendo produtos por condição
   * @param followUpType - Tipo de acompanhamento (none, annual, semiannual)
   * @param examType - Tipo de exame (conventional, pointOfCare)
   * @param condition - Nome da condição médica
   * @param productType - Tipo do produto (conventional ou pointOfCare)
   */
  const addProductsOfType = (
    products: AutoGeneratedProduct[],
    conditionProducts: ConditionProducts,
    followUpType: FollowUpType,
    examType: ExamType,
    condition: string,
    productType: 'conventional' | 'pointOfCare'
  ) => {
    const scenarioProducts = conditionProducts[followUpType]?.[productType]
    if (!scenarioProducts) return

    for (let index = 0; index < scenarioProducts.length; index++) {
      const product = scenarioProducts[index]
      products.push({
        id: `${condition}_${followUpType}_${examType}_${index}`,
        ...product,
        category: product.category as 'material' | 'service',
        condition,
        followUpType,
        examType
      })
    }
  }

  /**
   * Gera produtos para TODOS os tipos de acompanhamento (none, annual, semiannual)
   * Memoizado para evitar recalcular desnecessariamente
   * Recalcula apenas quando o tipo de exame ou condições mudam
   */
  const allProductsByFollowUp = useMemo(() => {
    // Inicializar estrutura para armazenar produtos de todos os cenários
    const allProducts: Record<FollowUpType, {
      conventional: AutoGeneratedProduct[]
      pointOfCare: AutoGeneratedProduct[]
    }> = {
      none: { conventional: [], pointOfCare: [] },
      annual: { conventional: [], pointOfCare: [] },
      semiannual: { conventional: [], pointOfCare: [] }
    }

    const examType = data.examData.type

    if (!examType) return

    const selectedConditions = Object.entries(data.conditions)
      .filter(([_, selected]) => selected)
      .map(([condition]) => condition)

    const followUpTypes: FollowUpType[] = ['none', 'annual', 'semiannual']

    // Gerar produtos para cada combinação de followup + condição
    for (const followUpType of followUpTypes) {
      for (const condition of selectedConditions) {
        const conditionProducts = productsByCondition[condition as keyof typeof productsByCondition]
        if (!conditionProducts) continue

        addProductsOfType(allProducts[followUpType].conventional, conditionProducts, followUpType, examType, condition, 'conventional')
        addProductsOfType(allProducts[followUpType].pointOfCare, conditionProducts, followUpType, examType, condition, 'pointOfCare')
      }
    }

    return allProducts
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data.examData.type, data.conditions])

  // Salvar os produtos calculados no contexto para uso no Step4
  useEffect(() => {
    updateExamData({
      ...data.examData,
      allProductsByFollowUp
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [allProductsByFollowUp])

  // Produtos do followup atualmente selecionado (para exibição)
  // ==================== SELEÇÃO DE PRODUTOS ATUAIS ====================

  if (!data.followUp.type) return

  const currentFollowUp = data.followUp.type
  const productsConventional = allProductsByFollowUp?.[currentFollowUp]?.conventional || []
  const productsPointOfCare = allProductsByFollowUp?.[currentFollowUp]?.pointOfCare || []

  /**
   * Consolida todos os produtos em uma única lista
   *
   * Funcionalidades:
   * - Consolida produtos com mesmo name/category somando quantidades
   * - Ordena primeiro por emissão (maior para menor), depois por quantidade (maior para menor)
   * - Retorna uma única lista de produtos consolidados
   *
   * @param products - Array de produtos a serem consolidados
   * @returns Array com produtos consolidados e ordenados
   */
  const consolidateProducts = (products: AutoGeneratedProduct[]): AutoGeneratedProduct[] => {
    const consolidated: Record<string, AutoGeneratedProduct> = {}

    // Somar quantidades de produtos com mesmo name e categoria
    for (const product of products) {
      const key = `${product.name}_${product.category}`

      if (consolidated[key]) {
        // Produto já existe - somar quantidade
        consolidated[key] = {
          ...consolidated[key],
          quantity: consolidated[key].quantity + product.quantity
        }
      } else {
        // Primeira ocorrência do produto
        consolidated[key] = { ...product }
      }
    }

    // Converter para array e ordenar: primeiro por emissão (maior para menor), depois por quantidade (maior para menor)
    return Object.values(consolidated).sort((a, b) => {
      // Calcular emissões totais de cada produto
      const emissionsA = a.emissionFactor * a.quantity
      const emissionsB = b.emissionFactor * b.quantity

      // Se as emissões forem diferentes, ordenar por emissão
      if (emissionsB !== emissionsA) {
        return emissionsB - emissionsA
      }
      // Se as emissões forem iguais, ordenar por quantidade
      return b.quantity - a.quantity
    })
  }

  // Consolidar produtos em uma única lista
  const consolidatedConventional = consolidateProducts(productsConventional)
  const consolidatedPointOfCare = consolidateProducts(productsPointOfCare)

  /**
   * Calcula emissões totais de um produto considerando o multiplicador de frequência
   * Fórmula: emissionFactor × quantity × frequencyMultiplier
   *
   * Multiplicadores:
   * - none: 1x (baseline)
   * - annual: 1x (uma vez ao ano)
   * - semiannual: 2x (duas vezes ao ano)
   */

  const handleScroll = (_event: React.UIEvent<HTMLDivElement> | ScrollState, examType: ExamType) => {
    if (examType !== data.examData.type) handleExamTypeChange(examType)
  }

  const renderExamTypeButton = (
    type: ExamType,
    imageSrc: string,
    imagePosition: 'left' | 'right'
  ) => {
    const isSelected = data.examData.type === type
    const label = type === 'conventional' ? t('conventional') : t('pointOfCare')

    return (
      <button
        type="button"
        onClick={() => handleExamTypeChange(type)}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault()
            handleExamTypeChange(type)
          }
        }}
        className={`
          cursor-pointer flex flex-row items-center
          ${imagePosition === 'right' ? 'justify-end' : 'justify-start'}
          ${isSelected ? 'scale-none' : 'hover:scale-105 active:scale-95'}
        `}>

        <div
          className={`
            rounded-full transition-colors
            ${isSelected
              ? 'border-[#52AE32] ring-2 ring-[#52AE32]'
              : 'border-white/20 hover:border-white/30'
            }
          `}>
          <div className="glass-container rounded-full!">
            <div className="glass-filter"></div>
            <div className="glass-overlay"></div>
            <div className="glass-specular"></div>
            <div className={`glass-content bg-black/40 flex-row! gap-0! p-0! ${imagePosition === 'right' ? 'flex-row-reverse! pl-4!' : 'pr-4!'}`}>
              <img src={imageSrc} alt="" className={`z-10 w-10 lg:w-16 h-10 lg:h-16 ${imagePosition === 'right' && '-ml-2'}`} />
              <p className="my-2.5 text-xs font-light">
                {label}
              </p>
            </div>
          </div>
        </div>
      </button>
    )
  }

  // Renderizar tabela consolidada de produtos
  const renderConsolidatedProductsTable = (products: AutoGeneratedProduct[]) => {
    // Verificar se algum produto tem emissões >= 1 kg
    const hasKgEmissions = products.some((p) => (p.emissionFactor * p.quantity) >= 1)
    const emissionUnit = hasKgEmissions ? 'kg CO₂e' : 'g CO₂e'
    const emissionMultiplier = hasKgEmissions ? 1 : 1000

    return (
      <div className="p-2">
        <div className="flex items-center justify-center bg-black/30">
          <h3 className="p-1 text-xs font-light text-white uppercase">
            {getConditionsTitle()}
          </h3>
        </div>

        <div className="my-10 mt-1 overflow-x-auto">
          <table className="w-full">
            <thead className="border-white border-b">
              <tr>
                <th className="text-xs w-[38%] pb-1 font-light text-left uppercase text-white">
                  {t('table.product')}
                </th>

                {/*
              <th className="text-[9px] w-[10%] pb-1 font-light text-right uppercase text-white">
                {t('table.category')}
              </th>
              */}

                {/*
              <th className="text-[9px] w-[22%] pb-1 font-light text-center uppercase text-white">
                {t('table.followUp')}
              </th>
              */}

                <th className="text-xs w-[12%] pb-1 font-light text-center uppercase text-white">
                  {t('table.quantity')}
                </th>
                <th className="pb-1 text-xs font-light text-center text-white">
                  <span className="uppercase">
                    {t('table.total')}
                  </span>
                  <span>
                    <br />
                    {emissionUnit}
                  </span>
                </th>
                {SHOW_FINAL_QUANTITY_COLUMN && (
                  <th className="text-[10px] w-[10%] pb-1 font-light text-right text-white">
                    Final
                  </th>
                )}
              </tr>
            </thead>
            <tbody className="divide-y divide-white/10">
              {products.map((product, index) => {
                const finalEmissions = product.emissionFactor * product.quantity
                return (
                  <tr key={`${product.id}-${index + 1}`} className="hover:bg-white/5">
                    <td className="py-3 text-xs font-light text-left text-white">
                      {getProductName(product.name, language)}
                    </td>
                    <td className="py-3 text-xs text-center text-white">
                      {`${product.quantity} ${product.category === 'material' ? 'und' : ''}`}
                    </td>
                    <td className="py-3 text-xs font-bold text-[#C8FF3C] text-center">
                      {(emissionMultiplier * finalEmissions).toFixed(3)}
                    </td>
                    {SHOW_FINAL_QUANTITY_COLUMN && (
                      <td
                        className="py-3 text-[10px] text-white text-right"
                        title={`${product.quantity} (und.) x ${followUpConfig[product.followUpType]?.frequencyMultiplier} (${data.followUp.type})`}>
                        Hover
                      </td>
                    )}
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      </div>
    )
  }

  // Configuração comum do scrollbar
  const scrollbarConfig = {
    minimalThumbYSize: 40,
    maximalThumbYSize: 40,
    disableTrackYWidthCompensation: true,
    className: 'space-y-2 h-full w-full',
    thumbYProps: {
      renderer: (props: ScrollbarElementProps) => {
        const { elementRef, ...restProps } = props
        return (
          <div
            {...restProps}
            ref={elementRef}
            style={{
              ...restProps.style,
              width: '40px',
              height: '40px',
              minWidth: '40px',
              minHeight: '40px',
              maxWidth: '40px',
              maxHeight: '40px',
              backgroundImage: 'url(ui/thumb2.svg)',
              backgroundSize: '40px 40px',
              backgroundRepeat: 'no-repeat',
              backgroundPosition: 'center',
              backgroundColor: '',
              border: '0.5px solid rgba(255, 255, 255, 0.2)',
              borderRadius: '50%',
              overflow: 'visible',
              display: 'flex',
              justifyContent: 'center',
              position: 'relative',
              left: '-14px',
              zIndex: 10
            }} />
        )
      }
    },
    trackYProps: {
      renderer: (props: ScrollbarElementProps) => {
        const { elementRef, ...restProps } = props
        return (
          <div
            {...restProps}
            ref={elementRef}
            style={{
              ...restProps.style,
              width: '14px',
              borderRadius: '100px',
              height: '97.5%',
              marginTop: '-5.5px',
              marginRight: '16.5px',
              overflow: 'visible',
              backgroundColor: 'rgba(0, 0, 0, 0.15)',
              border: '1px solid rgba(255, 255, 255, 0.1)'
            }} />
        )
      }
    }
  }

  // Renderizar scrollbar com produtos consolidados
  const renderProductsScrollbar = (examType: ExamType, products: AutoGeneratedProduct[]) => (
    <Scrollbar
      {...scrollbarConfig}
      onScroll={(e) => handleScroll(e, examType)}
      style={{ height: '100%', width: '100%' }}>
      <div className="pl-4 pr-10">
        {renderConsolidatedProductsTable(products)}
      </div>
    </Scrollbar>
  )

  // Renderizar botão de produto (conventional ou pointOfCare) com scrollbar
  const renderProductButton = (
    examType: ExamType,
    products: AutoGeneratedProduct[]
  ) => (
    <button
      type="button"
      className={`
        w-full cursor-pointer m-0.5 rounded-4xl transition-colors relative
        ${data.examData.type === examType
          ? 'border-[#52AE32] ring-2 ring-[#52AE32]'
          : 'border-white/20 hover:border-white/30'
        }
      `}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault()
          handleExamTypeChange(examType)
        }
      }}
      onClick={() => handleExamTypeChange(examType)}>
      <div className="glass-container h-[calc(min(100dvh,950px)-22.5rem)] min-h-50">
        {data.examData.type !== examType && (<div className="glass-filter"></div>)}
        <div className="glass-overlay"></div>
        <div className="glass-specular"></div>
        <div className="glass-content p-0! py-5! h-full justify-start!">
          {renderProductsScrollbar(examType, products)}
        </div>
      </div>
    </button>
  )

  return (
    <div className="mt-5.5 mb-6 w-full">
      {/* Warning message for "none" follow-up */}
      {data.followUp.type === 'none' && (
        <div className="flex items-center justify-center my-20">
          <div className="glass-container rounded-2xl max-w-200">
            <div className="glass-filter"></div>
            <div className="glass-overlay"></div>
            <div className="glass-specular"></div>
            <div className="glass-content">
              <div className="flex flex-col items-center gap-10 py-5">
                <div className="flex flex-col items-center justify-center gap-1">
                  <img src="ui/icon-warning.png" alt="Warning Sign" className="w-12 text-red-400" />
                  <h3 className="text-sm font-thin text-[#FFF15C]">
                    {t('noFollowUp.title')}
                  </h3>
                </div>
                <div className="flex items-center justify-center gap-1">
                  <img src="ui/icon-carbon.png" alt="Carbon Icon" className="h-16" />
                  <p className="mt-1 text-xs text-center max-w-50">
                    {t('noFollowUp.body')}
                  </p>
                  <img src="ui/icon-hospital.png" alt="Hospital Icon" className="h-14" />
                </div>
                <div className="flex items-center justify-center gap-1">
                  <p className="mt-1 text-sm text-center">
                    {t('noFollowUp.footer')}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {data.followUp.type !== 'none' && (
        <>
          {/* Exam Type Selection */}
          <div className="flex justify-center w-full gap-4 mb-4 select-none">
            {renderExamTypeButton('conventional', '/ui/icon-conventional.png', 'right')}
            {renderExamTypeButton('pointOfCare', '/ui/icon-pointofcare.png', 'left')}
          </div>

          {/* Products by Condition */}
          <div className="flex flex-col w-full h-full gap-4 lg:flex-row">
            {/* Mobile: show only selected exam type */}
            <div className="w-full lg:hidden">
              {data.examData.type === 'conventional' && renderProductButton('conventional', consolidatedConventional)}
              {data.examData.type === 'pointOfCare' && renderProductButton('pointOfCare', consolidatedPointOfCare)}
            </div>
            {/* Desktop: show both side by side */}
            <div className="hidden w-full h-full gap-4 lg:flex lg:flex-row">
              {renderProductButton('conventional', consolidatedConventional)}
              {renderProductButton('pointOfCare', consolidatedPointOfCare)}
            </div>
          </div>
        </>
      )}
    </div>
  )
}
