import type { MaterialProduct } from '@/types/materialsTable'
import type { ScrollbarElementProps } from '@/types/misc'
import type { AutoGeneratedProduct } from '@/types/patient'
import { useEffect } from 'react'
import { Scrollbar } from 'react-scrollbars-custom'
import CircularProgress from '@/components/CircularProgress'
import ComparisonCard from '@/components/ComparisonCard'
import ExportResultsButton from '@/components/ExportResults'
import { ProductsTable } from '@/components/ProductsTable'
import StatCard from '@/components/StatCard'
import useLanguage from '@/hooks/useLanguage'
import { usePatient } from '@/hooks/usePatient'
import { calculateTransportationEmissions } from '@/utils/transportationEmissions'

function PercentBadge({ percent, emissionValue, label, color, side = 'conventional', textColor, examType, ofEmission, differentUnits = false }: Readonly<{ percent: number, emissionValue: string, label: string, color: string, side?: 'conventional' | 'pointOfCare', textColor?: string, examType: 'conventional' | 'pointOfCare', ofEmission: string, differentUnits?: boolean }>) {
  const roundedClass = side === 'conventional'
    ? 'rounded-tr-md rounded-br-md'
    : 'rounded-tl-md rounded-bl-md'

  const lastSpaceIdx = emissionValue.lastIndexOf(' ')
  const valuePart = lastSpaceIdx > 0 ? emissionValue.substring(0, lastSpaceIdx) : emissionValue
  const unitPart = lastSpaceIdx > 0 ? emissionValue.substring(lastSpaceIdx + 1) : ''

  const alignmentClass = side === 'conventional' ? 'text-right' : 'text-left'

  const shouldShowBadge = !differentUnits && ((side === 'conventional' && examType === 'conventional') || (side === 'pointOfCare' && examType === 'pointOfCare'))

  return (
    <div className="flex flex-col">
      <div className={`min-h-8 flex items-center ${shouldShowBadge ? '' : 'invisible'}`}>
        {shouldShowBadge && (
          <div
            className={`
              px-3 py-1 w-full text-[11px] font-semibold text-white uppercase
              ${roundedClass} ${side === 'conventional' ? 'text-right' : 'text-left'}
            `}
            style={{
              background: color,
              letterSpacing: '0.5px'
            }}>
            {/* ${examType === 'conventional' ? '+' : '-'} */}
            {`${percent}% ${ofEmission}`}
          </div>
        )}
      </div>

      <div className={` ${alignmentClass} `}>
        <div className={`text-xl font-extrabold ${textColor || 'text-white'}`}>{valuePart}</div>
        {unitPart && (
          <div className={`text-[11px] mt-0.5 uppercase font-light ${textColor || 'text-white'}`} style={{ position: 'relative', bottom: 5 }}>{unitPart}</div>
        )}
        <div className={`text-[11px] uppercase ${textColor || 'text-white'}`}>{label}</div>
      </div>
    </div>
  )
}

function createThumbRenderer(isHorizontal: boolean) {
  return (props: ScrollbarElementProps) => {
    const { elementRef, ...restProps } = props
    const thumbStyle = isHorizontal
      ? {
          width: '35px',
          height: '35px',
          backgroundImage: 'url(ui/thumb-horizontal.svg)',
          position: 'absolute' as const,
          top: '-12px'
        }
      : {
          width: '35px',
          height: '35px',
          backgroundImage: 'url(ui/thumb2.svg)',
          position: 'relative' as const,
          left: '-13.2px'
        }

    return (
      <div
        {...restProps}
        ref={elementRef}
        style={{
          ...restProps.style,
          ...thumbStyle,
          minWidth: '35px',
          minHeight: '35px',
          maxWidth: '35px',
          maxHeight: '35px',
          backgroundSize: '35px 35px',
          backgroundRepeat: 'no-repeat',
          backgroundPosition: 'center',
          backgroundColor: 'rgba(0, 0, 0, 0.1)',
          border: '0.5px solid rgba(255, 255, 255, 0.3)',
          borderRadius: '50%',
          overflow: 'visible',
          display: 'flex',
          opacity: '0.8',
          justifyContent: 'center',
          zIndex: 10
        }} />
    )
  }
}

// Componente para tracks do scrollbar
function createTrackRenderer(isHorizontal: boolean) {
  return (props: ScrollbarElementProps) => {
    const { elementRef, ...restProps } = props
    const trackStyle = isHorizontal
      ? {
          width: '96.5%',
          height: '12px',
          bottom: '4px'
        }
      : {
          width: '10px',
          height: '82.5%',
          marginTop: '27.5px',
          marginRight: typeof window !== 'undefined' && window.innerWidth >= 1024 ? '23px' : '18px'
        }

    return (
      <div
        {...restProps}
        ref={elementRef}
        style={{
          ...restProps.style,
          ...trackStyle,
          borderRadius: '100px',
          overflow: 'visible',
          backgroundColor: 'rgba(0, 0, 0, 0.15)',
          border: '1px solid rgba(255, 255, 255, 0.1)'
        }} />
    )
  }
}

export function PatientStep5() {
  const { data, getConditionsTitle, updateExamData } = usePatient()
  const { t } = useLanguage()

  // Garantir que examType seja 'conventional' quando followUp é 'none'
  useEffect(() => {
    if (data.followUp.type === 'none' && data.examData.type !== 'conventional') {
      updateExamData({
        ...data.examData,
        type: 'conventional'
      })
    }
  }, [data.followUp.type, data.examData, updateExamData])

  function getExamTypeSustainabilitySuggestion(type: 'conventional' | 'pointOfCare') {
    if (data.followUp.type === 'none') {
      return { description: t('recommendedSuggestion.none') }
    }

    if (type === 'conventional') {
      return { description: t('suggestions.suggestion04.description') }
    }

    return { description: t('suggestions.suggestion05.description') }
  }

  if (!data.results) return null

  const followUpType = data.followUp.type
  const examType = data.examData.type
  const frequencyMultiplier = followUpType === 'semiannual' ? 2 : 1

  if (!followUpType || !examType) return null

  /**
   * Formata valor de emissões para exibição
   * Se valor < 1 kg, converte para gramas
   * Caso contrário, mantém em kg
   */
  const formatEmissions = (kgValue: number): { value: string, unit: string } => {
    if (kgValue < 1) {
      const grams = kgValue * 1000
      return {
        value: grams.toFixed(3),
        unit: 'g CO₂e'
      }
    }
    return {
      value: kgValue.toFixed(2),
      unit: 'kg CO₂e'
    }
  }

  // Handler para mudança de tipo de exame
  const handleExamTypeChange = (type: 'conventional' | 'pointOfCare') => {
    updateExamData({
      ...data.examData,
      type
    })
  }

  const selectedConditions = [
    data.conditions.lowerBackPain,
    data.conditions.hypertension,
    data.conditions.diabetes,
    data.conditions.overweight
  ].filter(Boolean).length

  // Calcular emissões específicas de Point of Care
  const calculatePointOfCareEmissions = () => {
    if (!data.examData.allProductsByFollowUp) return 0

    let products: AutoGeneratedProduct[] = []

    if (['annual', 'semiannual'].includes(followUpType)) {
      products = data.examData.allProductsByFollowUp[followUpType].pointOfCare
    }

    // Para badges, sempre usar 'annual' para criar contraste com 'none'
    if (followUpType === 'none') {
      products = data.examData.allProductsByFollowUp.annual.pointOfCare
    }

    return products.reduce((sum: number, p) => {
      return sum + (p.emissionFactor * p.quantity * frequencyMultiplier)
    }, 0)
  }

  // Calcular emissões específicas de Conventional
  const calculateConventionalEmissions = () => {
    if (!data.examData.allProductsByFollowUp) return 0

    let products: AutoGeneratedProduct[] = []

    if (['annual', 'semiannual'].includes(followUpType)) {
      products = data.examData.allProductsByFollowUp[followUpType].conventional
    }

    // Para badges, sempre usar 'annual' para criar contraste com 'none'
    if (followUpType === 'none') {
      products = data.examData.allProductsByFollowUp.annual.conventional
    }

    return products.reduce((sum: number, p) => {
      return sum + (p.emissionFactor * p.quantity * frequencyMultiplier)
    }, 0)
  }

  // Calcular emissões de transporte
  const getTransportationEmissions = () => {
    // Se não há acompanhamento, não há transporte
    if (followUpType === 'none') return 0

    return calculateTransportationEmissions(
      data.transportation.type,
      data.transportation.distanceKm
    )
  }

  // Calcular emissões médicas do cenário atual (followUp + examType selecionados)
  const calculateCurrentMedicalEmissions = () => {
    if (!data.examData.allProductsByFollowUp) return 0

    const currentProducts = data.examData.allProductsByFollowUp[followUpType][examType]

    return currentProducts.reduce((sum: number, p) => {
      return sum + (p.emissionFactor * p.quantity * frequencyMultiplier)
    }, 0)
  }
  const calculateWithoutFollowUpMedicalEmissions = () => {
    if (!data.examData.allProductsByFollowUp) return 0

    const products = data.examData.allProductsByFollowUp.none[examType]

    return products.reduce((sum: number, p) => {
      return sum + (p.emissionFactor * p.quantity)
    }, 0)
  }

  /**
   * ==================== EMISSÕES SEPARADAS POR TIPO ====================
   * Valores disponíveis para acesso individual:
   *
   * TRANSPORTE:
   * - transportationEmissions: Emissões de transporte (baseado em tipo + distância)
   *
   * EMISSÕES MÉDICAS (apenas produtos):
   * - currentMedicalEmissions: Emissões médicas do cenário atual (followUp + examType)
   * - oppositeExamMedicalEmissions: Emissões médicas do tipo de exame oposto
   * - withoutFollowUpMedicalEmissions: Emissões médicas sem acompanhamento
   * - conventionalEmissions: Emissões de exames convencionais (annual)
   * - pointOfCareEmissions: Emissões de exames Point of Care (annual)
   *
   * EMISSÕES TOTAIS (médicas + transporte):
   * - currentEmissions: Total do cenário atual
   * - oppositeExamEmissions: Total do exame oposto
   * - withoutFollowUpEmissions: Total sem acompanhamento
   * =====================================================================
   */

  // Emissões de transporte
  const transportationEmissions = getTransportationEmissions()

  // Emissões médicas (apenas produtos)
  const currentMedicalEmissions = calculateCurrentMedicalEmissions()
  const withoutFollowUpMedicalEmissions = calculateWithoutFollowUpMedicalEmissions()
  const conventionalEmissions = calculateConventionalEmissions()
  const pointOfCareEmissions = calculatePointOfCareEmissions()

  // Emissões totais (médicas + transporte) - Use estas para exibição
  const currentEmissions = currentMedicalEmissions
  const withoutFollowUpEmissions = withoutFollowUpMedicalEmissions

  // Calcular emissões para comparação "Com Acompanhamento" vs "Sem Acompanhamento"
  const getFollowUpComparisonEmissions = () => {
    if (followUpType === 'none') {
      // Quando está vendo "none", mostrar como seria com annual point of care
      const annualPoCProducts = data.examData.allProductsByFollowUp?.annual.pointOfCare || []
      return annualPoCProducts.reduce((sum: number, p) => {
        return sum + (p.emissionFactor * p.quantity)
      }, 0)
    }
    // Quando está em annual ou semiannual, mostrar o cenário atual
    return currentMedicalEmissions
  }

  const followUpComparisonEmissions = getFollowUpComparisonEmissions()

  // Calcular emissões evitáveis por internações
  const calculateHospitalizationEmissions = () => {
    if (!data.examData.allProductsByFollowUp) return 0
    return withoutFollowUpEmissions - followUpComparisonEmissions
  }

  const hospitalizationEmissions = calculateHospitalizationEmissions()

  // Calcular percentual de redução com follow-up
  // const followUpReductionPercent = withoutFollowUpEmissions > 0
  //   ? (((withoutFollowUpEmissions - followUpComparisonEmissions) / withoutFollowUpEmissions) * 100).toFixed(2)
  //   : 0

  // Usar sugestões do contexto (calculadas no PatientContext)
  const dynamicSuggestions = data.results.suggestions

  // Obter produtos do tipo de exame atual
  const getCurrentProducts = (): MaterialProduct[] => {
    if (!data.examData.allProductsByFollowUp) return []

    // Verificar se existem produtos para este follow-up e tipo de exame
    const products = data.examData.allProductsByFollowUp[followUpType]?.[examType]

    return products || []
  }

  // Renderizar botões de seleção de tipo de exame (igual ao PatientStep3)
  const renderExamTypeButton = (
    type: 'conventional' | 'pointOfCare',
    imageSrc: string,
    imagePosition: 'left' | 'right'
  ) => {
    const isSelected = examType === type
    const label = type === 'conventional' ? t('conventional') : t('pointOfCare')

    return (
      <button
        type="button"
        onClick={() => handleExamTypeChange(type)}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault()
            handleExamTypeChange(type)
          }
        }}
        className={`
          cursor-pointer flex flex-row items-center
          ${imagePosition === 'right' ? 'justify-end' : 'justify-start'}
          ${isSelected ? 'scale-none' : 'hover:scale-105 active:scale-95'}
        `}>

        <div
          className={`
            rounded-full transition-colors
            ${isSelected
              ? 'border-[#52AE32] ring-2 ring-[#52AE32]'
              : 'border-white/20 hover:border-white/30'
            }
          `}>
          <div className="glass-container rounded-full!">
            <div className="glass-filter"></div>
            <div className="glass-overlay"></div>
            <div className="glass-specular"></div>
            <div
              className={`
                glass-content flex-row! gap-0! p-0!
                ${isSelected ? 'bg-black/40' : 'text-white/60!'}
                ${imagePosition === 'right' ? 'flex-row-reverse! pl-4!' : 'pr-4!'}
              `}>
              <img
                src={imageSrc}
                alt=""
                className={`
                  z-10 w-10 h-10 lg:w-16 lg:h-16
                  ${!isSelected && 'opacity-50'}
                  ${imagePosition === 'right' && '-ml-2'}
                `} />
              <p className="my-2.5 text-xs font-light">
                {label}
              </p>
            </div>
          </div>
        </div>
      </button>
    )
  }

  const totalEmissionConventional = conventionalEmissions + transportationEmissions
  const totalEmissionPointOfCare = pointOfCareEmissions + transportationEmissions

  const totalForComparison = totalEmissionConventional + totalEmissionPointOfCare
  const conventionalSharePercent = totalForComparison > 0 ? Math.round((totalEmissionConventional / totalForComparison) * 100) : 0
  const pointOfCareSharePercent = totalForComparison > 0 ? Math.round((totalEmissionPointOfCare / totalForComparison) * 100) : 0

  // Definir cores baseadas no tipo de exame selecionado
  const conventionalTextColor = examType === 'conventional' ? 'text-red-400' : 'text-white'
  const pointOfCareTextColor = examType === 'pointOfCare' ? 'text-[#52ae32]' : 'text-white'

  return (
    <div className="mt-10.5 lg:mt-13.5 mb-0 lg:mb-4 relative h-[calc(min(100dvh,950px)-15rem)] lg:h-[calc(min(100dvh,950px)-19.25rem)] min-h-100 w-full">
      {/* Export button in top right corner */}
      <div className="absolute z-20 -top-10 right-10 lg:right-16">
        <ExportResultsButton />
      </div>

      {/* Exam Type Selection - Only show if follow-up is not 'none' */}
      {data.followUp.type !== 'none' && (
        <div className="absolute top-0 flex justify-center gap-4 mb-4 transform -translate-x-1/2 -translate-y-1/2 select-none left-1/2 z-15">
          {renderExamTypeButton('conventional', '/ui/icon-conventional.png', 'right')}
          {renderExamTypeButton('pointOfCare', '/ui/icon-pointofcare.png', 'left')}
        </div>
      )}

      <div className="glass-container border-3 border-[#52AE32] rounded-[35px]! h-full">
        <div className="glass-filter rounded-4xl!"></div>
        <div className="glass-overlay rounded-4xl!"></div>
        <div className="glass-specular rounded-4xl!"></div>
        <div className="glass-content p-0! rounded-sm! inset-shadow-bolder h-full">
          <Scrollbar
            thumbYProps={{ renderer: createThumbRenderer(false) }}
            trackYProps={{ renderer: createTrackRenderer(false) }}
            minimalThumbYSize={35}
            maximalThumbYSize={35}
            disableTrackYWidthCompensation={true}
            style={{ height: '100%', width: '100%' }}>
            <div className="pl-4 pr-12 pt-6 pb-10 lg:px-14 lg:pt-15 min-w-fit">
              {/* Mobile: Sustainability Recommendation at Top */}
              <div className="block mb-6 lg:hidden">
                <div className="glass-container gap-0!">
                  {/* <div className="glass-filter"></div> */}
                  <div className="glass-overlay"></div>
                  <div className="glass-specular"></div>
                  <div className="glass-content">
                    <div className="flex items-center py-4 px-2">
                      <div className="flex flex-col flex-1 min-w-0">
                        <div className="z-10 w-full p-2 font-bold text-left text-white font-krona-one text-md">
                          {t('step5.recommendations')}
                        </div>
                        <div className="flex flex-col p-2 overflow-y-auto scrollbar-dark ">
                          <p className="text-[12px] text-white text-left leading-relaxed">
                            {getExamTypeSustainabilitySuggestion(examType).description}
                          </p>
                        </div>
                      </div>
                      <img src="ui/suggestions/icon-peace.png" alt="World Icon" className="mt-3 w-30" />
                    </div>
                  </div>
                </div>
              </div>

              {/* Grid Principal: Responsivo - 3 colunas em desktop, 1 coluna em mobile */}
              <div className="grid gap-6 h-full xl:grid-cols-[minmax(220px,4fr)_minmax(320px,7fr)_minmax(400px,9fr)] lg:grid-cols-[minmax(220px,4fr)_minmax(300px,7fr)_minmax(350px,9fr)] md:grid-cols-[1fr_2fr] sm:grid-cols-[1fr_2fr] grid-cols-1">
                <div className="flex flex-col justify-between order-1 gap-6">
                  <StatCard
                    value={String(
                      data.examData.allProductsByFollowUp
                        ? data.examData.allProductsByFollowUp[followUpType][examType]
                          .reduce((sum, p) => sum + p.quantity, 0) * frequencyMultiplier
                        : 0
                    ).padStart(2, '0')}
                    icon="/ui/icon-products.png"
                    label={t('step5.productsGenerated')}
                    size="11px" />

                  <StatCard
                    value={String(hospitalizationEmissions.toFixed(1)).padStart(2, '0')}
                    icon="/ui/icon-hospital.png"
                    size="10px"
                    label={t('step5.emissionsByHospitalizations')}
                    showUnity
                    unit={formatEmissions(hospitalizationEmissions).unit} />

                  <StatCard
                    value={String(Math.round(hospitalizationEmissions / 24)).padStart(2, '0')}
                    icon="/ui/icon-tree.png"
                    size="11px"
                    label={t('step5.equivalentTrees')} />

                  <StatCard
                    value={String(selectedConditions).padStart(2, '0')}
                    icon="/ui/icon-group.png"
                    size="11px"
                    label={t('step5.chronicConditions')
                      .replace('{plural}', selectedConditions > 1 ? 's' : '')
                      .replace('{plural}', selectedConditions > 1 ? 's' : '')} />
                </div>

                {/* COLUNA 2 (Meio): Cards de Comparação */}
                <div className="flex flex-col order-2 gap-6 min-w-0">
                  {/* Exam Type Comparison */}
                  <div className="glass-container rounded-2xl w-full">
                    {/* <div className="glass-filter"></div> */}
                    <div className="glass-overlay"></div>
                    <div className="glass-specular"></div>
                    <div className="glass-content py-0 lg:py-10! flex! gap-0! flex-row!">
                      <img src="ui/icon-carbon.png" alt="Carbon Icon" className="w-15 lg:w-20 shrink-0" />
                      <div className="glass-container rounded-2xl flex-1 min-w-0">
                        {/* <div className="glass-filter"></div> */}
                        <div className="glass-overlay"></div>
                        <div className="glass-specular"></div>
                        <div className="glass-content py-2! lg:py-5!  bg-black/20">
                          <div className="flex flex-col text-center ">
                            <p className="text-xl lg:text-4xl font-extrabold! font-kreon">
                              {`
                                ${formatEmissions(currentEmissions + transportationEmissions).value}
                                ${formatEmissions(currentEmissions + transportationEmissions).unit}
                              `}
                            </p>
                            <p className="font-kreon text-sm lg:text-lg font-bold! text-[#52AE32]">
                              {t('step5.totalEmissions')}
                            </p>
                            {followUpType !== 'none' && (
                              <p className="mt-2 text-xs">
                                <span className="text-white/60">
                                  {t('step5.productsServicesLabel')}
                                  {' '}
                                </span>
                                {`
                                  ${formatEmissions(currentEmissions).value}
                                  ${formatEmissions(currentEmissions).unit}
                                `}
                                <br />
                                <span className="text-white/60">
                                  {t('step5.transportationLabel')}
                                  {' '}
                                </span>
                                {`
                                  ${formatEmissions(transportationEmissions).value}
                                  ${formatEmissions(transportationEmissions).unit}
                                `}
                              </p>
                            )}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Horizontal Bar Chart Visualization - Exams side by side */}
                  <div className="glass-container w-full min-w-0">
                    {/* <div className="glass-filter"></div> */}
                    <div className="glass-overlay"></div>
                    <div className="glass-specular"></div>
                    <div className="glass-content px-0! gap-0! lg:gap-4!">
                      <div className="flex flex-row items-center border-b border-white/50 w-[80%] gap-1">
                        {/* <img src="ui/icon-chart.png" alt="" className="w-8" /> */}
                        <h3 className="text-xs font-light text-white uppercase">
                          {t('step5.visualComparison')}
                        </h3>
                      </div>

                      <div className="flex flex-row items-center justify-between w-full mt-4 mb-2">
                        {/* Convencional */}
                        <div className="flex flex-col flex-1 items-right">
                          <PercentBadge
                            percent={conventionalSharePercent}
                            emissionValue={`${formatEmissions(conventionalEmissions + transportationEmissions).value} ${formatEmissions(conventionalEmissions + transportationEmissions).unit}`}
                            label={t('conventional')}
                            color="#DC0B0B"
                            side="conventional"
                            textColor={conventionalTextColor}
                            examType={examType}
                            ofEmission={t('step5.ofEmission')} />
                        </div>

                        {/* Percentual no meio: circular progress */}
                        <div className="flex items-center justify-center px-2">
                          <CircularProgress
                            percent={examType === 'conventional' ? conventionalSharePercent : pointOfCareSharePercent}
                            size={100}
                            strokeWidth={10}
                            color={examType === 'conventional' ? '#DC0B0B' : '#52AE32'}
                            isPointOfCare={examType === 'pointOfCare'} />
                        </div>

                        {/* Point of Care */}
                        <div className="flex flex-col flex-1 items-left">
                          <PercentBadge
                            percent={pointOfCareSharePercent}
                            emissionValue={`${formatEmissions(pointOfCareEmissions + transportationEmissions).value} ${formatEmissions(pointOfCareEmissions + transportationEmissions).unit}`}
                            label={t('pointOfCare')}
                            color="#52ae32"
                            side="pointOfCare"
                            textColor={pointOfCareTextColor}
                            examType={examType}
                            ofEmission={t('step5.ofEmission')} />
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Follow-up Comparison */}
                  <ComparisonCard title={t('step5.followUpImpact')} icon="ui/icon-arrow.png">
                    <div className="flex flex-wrap lg:flex-nowrap justify-between gap-2 lg:gap-4 w-full">
                      <div className="flex flex-col flex-1 min-w-30 items-center gap-2">
                        <span className="text-xs font-semibold text-center text-green-200">
                          <span className="text-xl lg:text-2xl">
                            {formatEmissions(followUpComparisonEmissions + transportationEmissions).value}
                          </span>
                          <br />
                          {formatEmissions(followUpComparisonEmissions + transportationEmissions).unit}
                        </span>
                        <img src="/ui/hospital_2.png" alt="With Follow-up" className="h-10 w-7 lg:w-13 lg:h-16 hospital-image" />
                        <div className="flex flex-col justify-center min-h-14.5 w-full px-1 lg:px-4 py-2 bg-[#0B79DC] rounded-[40px] text-white/90 text-center text-[10px] lg:text-sm leading-tight wrap-break-word hyphens-auto">
                          {t('step5.withFollowUp')}
                          <br />
                          <span className="text-[9px] block">
                            {followUpType === 'none' && (
                              <>
                                {`( ${t('pointOfCare')}`}
                                <span className="capitalize">{` ${t('step1.annual')}`}</span>
                                {` )`}
                              </>
                            )}

                            {followUpType !== 'none' && (
                              `( ${examType === 'conventional' ? t('conventional') : t('pointOfCare')} )`
                            )}
                          </span>
                        </div>
                      </div>
                      <div className="flex flex-col flex-1 min-w-30 items-center gap-2">
                        <span className="text-xs font-semibold text-center text-red-200">
                          <span className="text-xl lg:text-2xl">
                            {formatEmissions(withoutFollowUpEmissions).value}
                          </span>
                          <br />
                          {formatEmissions(withoutFollowUpEmissions).unit}
                        </span>
                        <img src="/ui/hospital_1.png" alt="Without Follow-up" className="h-10 w-7 lg:w-13 lg:h-16 hospital-image" />
                        <div className="flex flex-col justify-center min-h-14.5 w-full px-1 lg:px-4 py-2 bg-[#DC0B0B] rounded-[40px] text-white/90 text-center text-[10px] lg:text-sm leading-tight wrap-break-word hyphens-auto">
                          <p>{t('step5.withoutFollowUp')}</p>
                        </div>
                      </div>
                    </div>
                    {/* <div className="flex text-[#3AD0F5] items-center gap-2 text-sm">
                      {t('step5.different')}
                      <hr className="w-30 h-[0.1px] border-[#00CCFF]/40 border-b-[0.1px]" />
                      <span className="text-2xl font-bold">
                        {`${followUpReductionPercent}%`}
                      </span>
                    </div> */}
                  </ComparisonCard>
                </div>

                {/* COLUNA 3 (Direita): Grid com 2 Linhas (Sustentabilidade | Tabela) */}
                <div className="grid grid-rows-[auto_1fr] gap-6 lg:order-3 lg:col-span-1 order-3 col-span-2">
                  {/* Exam Type Sustainability Suggestion - Hidden on mobile, shown on desktop */}
                  <div className="hidden! lg:block! glass-container w-full gap-0!">
                    {/* <div className="glass-filter"></div> */}
                    <div className="glass-overlay"></div>
                    <div className="glass-specular"></div>
                    <div className="glass-content w-full!">
                      <div className="flex items-center justify-around w-full min-h-40 py-4 px-2">
                        <div className="flex flex-col flex-1 min-w-0">
                          <div className="z-10 w-full p-2 font-bold text-left text-white uppercase font-krona-one text-md">
                            {t('step5.recommendations')}
                          </div>
                          <div className="flex flex-col p-2 overflow-y-auto scrollbar-dark">
                            <p className="text-[12px] text-white text-left leading-relaxed">
                              {getExamTypeSustainabilitySuggestion(examType).description}
                            </p>
                          </div>
                        </div>
                        <img src="ui/suggestions/icon-peace.png" alt="World Icon" className="mt-3 w-30" />
                      </div>
                    </div>
                  </div>

                  {/* Materials Table - Only show if follow-up is not 'none' */}
                  <div className="glass-container w-full min-h-75 lg:min-h-0">
                    {/* <div className="glass-filter"></div> */}
                    <div className="glass-overlay"></div>
                    <div className="glass-specular"></div>
                    <div className="glass-content p-0! w-full h-full">
                      <ProductsTable
                        products={getCurrentProducts()}
                        config={{
                          examType,
                          followUpType,
                          title: getConditionsTitle()
                        }} />
                    </div>
                  </div>
                </div>
              </div>

              {/* Suggestions */}
              <div className="glass-container flex-col h-[272.5px] mt-6 w-full">
                <div className="font-krona-one bg-[#52AE32] text-white uppercase z-10 w-full p-2 font-bold text-left pl-8 text-md">
                  {t('step5.reductionSuggestions')}
                </div>
                {/* <div className="glass-filter"></div> */}
                <div className="glass-overlay"></div>
                <div className="glass-specular"></div>
                <div className="glass-content w-full mt-2.5">
                  <Scrollbar
                    minimalThumbXSize={35}
                    maximalThumbXSize={35}
                    disableTrackYWidthCompensation={true}
                    disableTrackXWidthCompensation={true}
                    style={{ width: '100%', height: '100%' }}
                    thumbXProps={{ renderer: createThumbRenderer(true) }}
                    trackXProps={{ renderer: createTrackRenderer(true) }}>
                    <div className="flex flex-row gap-x-6">
                      {dynamicSuggestions.map((suggestion) => {
                        const title = suggestion.titleKey ? t(suggestion.titleKey) : ''
                        const description = suggestion.descriptionKey ? t(suggestion.descriptionKey) : ''
                        const subDescriptionText = suggestion.subDescriptionKey ? t(suggestion.subDescriptionKey) : ''
                        const hasSubDescription = subDescriptionText && subDescriptionText !== suggestion.subDescriptionKey

                        return (
                          <div key={suggestion.translationKey} className="min-w-50 h-20">
                            <div className="glass-container">
                              {/* <div className="glass-filter"></div> */}
                              <div className="glass-overlay"></div>
                              <div className="glass-specular"></div>
                              <div className="glass-content p-0! py-6! px-5! h-39.5">
                                <div className="flex flex-col h-28.75 overflow-y-auto scrollbar-dark pr-2">
                                  {title && (
                                    <div className="flex items-center gap-2 mb-2">
                                      <p className="text-[11px] text-[#52AE32] font-semibold">
                                        {title}
                                      </p>
                                    </div>
                                  )}
                                  {description && (
                                    <p className="text-[12px] text-white text-left leading-relaxed mb-0.5">
                                      {description}
                                    </p>
                                  )}
                                  {hasSubDescription && (
                                    <p className="text-[11px] text-green-300/90 text-left leading-relaxed border-l-2 border-green-400/50 pl-2">
                                      {subDescriptionText}
                                    </p>
                                  )}
                                </div>
                                <div>
                                  <div className="absolute -bottom-4.5 -right-2.5">
                                    <img src={suggestion.iconPath} alt={title} className="w-25 opacity-30" />
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        )
                      })}
                    </div>
                  </Scrollbar>
                </div>
              </div>
            </div>
          </Scrollbar>
        </div>
      </div>
    </div>
  )
}
