import type { DisposalType, ExamType, FollowUpType, TransportationType } from '@/types/shared.js'

// Reusable union type aliases to satisfy lint rules preferring aliases over inline unions
export type EmergencyVisits = 'none' | 'once' | 'twiceOrMore'
export type YesNoUnknown = 'yes' | 'no' | 'unknown'
export type BariatricSurgery = 'no' | 'lessThan1Year' | 'moreThan1Year'
export type OverweightRecommendation = 'formallyIndicated' | 'considered' | 'no'
export type OverweightMedication = 'no' | 'oral' | 'injectable' | 'both'
export type LowerBackPainMedication = 'daily' | 'occasional' | 'no' | 'unknown'

export interface PatientTransportation {
  type: TransportationType | undefined
  distanceKm: number
}

export interface PatientConditions {
  lowerBackPain: boolean
  hypertension: boolean
  diabetes: boolean
  overweight: boolean
  noChronicConditions: boolean
  hypertensionEmergencyVisits?: EmergencyVisits
  hypertensionControlled?: YesNoUnknown
  hypertensionTreatment?: string[]
  diabetesControlled?: YesNoUnknown
  diabetesEmergencyVisits?: EmergencyVisits
  diabetesTreatment?: string[]
  overweightBariatricSurgery?: BariatricSurgery
  overweightRecommendation?: OverweightRecommendation
  overweightMedication?: OverweightMedication
  overweightMeasures?: string[]
  lowerBackPainMedication?: LowerBackPainMedication
  lowerBackPainImagingExams?: { [exam: string]: number | boolean }
  lowerBackPainEmergencyVisits?: EmergencyVisits
}

export interface PatientFollowUp {
  type: FollowUpType | undefined
}

export interface PatientProduct {
  id: string
  name: string
  category: string
  emissionFactor: number
  quantity: number
}

export interface PatientDisposalData {
  products: {
    [productId: string]: DisposalType
  }
}

export interface AutoGeneratedProduct {
  id: string
  name: string
  category: 'material' | 'service'
  emissionFactor: number
  quantity: number
  condition: string
  followUpType: string
  examType: string
}

export interface ProductsByFollowUp {
  conventional: AutoGeneratedProduct[]
  pointOfCare: AutoGeneratedProduct[]
}

export interface AllProductsByFollowUp {
  none: ProductsByFollowUp
  annual: ProductsByFollowUp
  semiannual: ProductsByFollowUp
}

export interface PatientExamData {
  type: ExamType | undefined
  products: PatientProduct[]
  allProductsByFollowUp?: AllProductsByFollowUp
}

export interface PatientSuggestions {
  pretitle: string
  title: string
  reduction: string
  description: string
  subDescription?: string
  translationKey: string
  titleKey?: string
  descriptionKey?: string
  subDescriptionKey?: string
  iconPath?: string
  priority: number // Prioridades: 1 = muito alta, 2 = alta, 3 = média, 4 = baixa
}

export interface PatientResults {
  totalEmissions: number
  transportationEmissions: number
  medicalEmissions: number
  avoidableEmissions: number
  conventionalVsPointOfCare: {
    conventional: number
    pointOfCare: number
  }
  withVsWithoutFollowUp: {
    with: number
    without: number
  }
  recommendations: string[]
  suggestions: PatientSuggestions[]
  emissionsByDisease?: Record<string, number>
}

export interface PatientData {
  language: 'br' | 'en' | 'es' | 'cn'
  transportation: PatientTransportation
  conditions: PatientConditions
  followUp: PatientFollowUp
  examData: PatientExamData
  disposalData: PatientDisposalData
  results: PatientResults | null
  anamnesisId?: string
  questionnaireData?: PatientQuestionnaireData
}

export interface PatientQuestionnaireData {
  age: number
  gender: 'feminino' | 'masculino' | 'outro'
  walk_days: number
  walk_minutes: number
  mod_days: number
  mod_minutes: number
  vig_days: number
  vig_minutes: number
  veg_portions: number
  fruit_portions: number
  ultra_processed: number
  smoke_status: string
  alcohol_days_week: number
  alcohol_drinks_day: number
  followup: string
  blood_tests_year: number
  lab_type: string
}
