import type { BaseProduct } from '@/constants/healthcareData'
import type { ScrollbarElementProps } from '@/types/misc'
import type { AutoGeneratedProduct } from '@/types/patient'
import type { ExamType } from '@/types/shared'
import { useMemo } from 'react'
import { Scrollbar } from 'react-scrollbars-custom'
import CircularProgress from '@/components/CircularProgress'
import ComparisonCard from '@/components/ComparisonCard'
import { ProductsTable } from '@/components/ProductsTable'
import StatCard from '@/components/StatCard'
import SectionHeader from '@/components/ui/section-header'
import { FREQUENCY_MULTIPLIERS } from '@/constants/emissions'
import { PRODUCTS_BY_CONDITION } from '@/constants/healthcareData'
import { getPopulationSuggestions } from '@/data/populationSuggestions'
import useLanguage from '@/hooks/useLanguage'
import { usePopulation } from '@/hooks/usePopulation'

interface ConditionProducts {
  [followUpType: string]: {
    conventional?: BaseProduct[]
    pointOfCare?: BaseProduct[]
  }
}

interface FollowUpDistribution {
  none: number
  annual: number
  semiannual: number
}

function PercentBadge({ percent, emissionValue, label, color, side = 'conventional', textColor, examType, ofEmission, differentUnits = false }: Readonly<{ percent: number, emissionValue: string, label: string, color: string, side?: 'conventional' | 'pointOfCare', textColor?: string, examType: 'conventional' | 'pointOfCare', ofEmission: string, differentUnits?: boolean }>) {
  const roundedClass = side === 'conventional'
    ? 'rounded-tr-md rounded-br-md'
    : 'rounded-tl-md rounded-bl-md'

  const lastSpaceIdx = emissionValue.lastIndexOf(' ')
  const valuePart = lastSpaceIdx > 0 ? emissionValue.substring(0, lastSpaceIdx) : emissionValue
  const unitPart = lastSpaceIdx > 0 ? emissionValue.substring(lastSpaceIdx + 1) : ''

  const alignmentClass = side === 'conventional' ? 'text-right' : 'text-left'

  const shouldShowBadge = !differentUnits && ((side === 'conventional' && examType === 'conventional') || (side === 'pointOfCare' && examType === 'pointOfCare'))

  return (
    <div className="flex flex-col">
      <div className={`min-h-8 flex items-center ${shouldShowBadge ? '' : 'invisible'}`}>
        {shouldShowBadge && (
          <div
            className={`
              px-3 py-1 w-full text-[11px] font-semibold text-white uppercase
              ${roundedClass} ${side === 'conventional' ? 'text-right' : 'text-left'}
            `}
            style={{
              background: color,
              letterSpacing: '0.5px'
            }}>
            {/* ${examType === 'conventional' ? '+' : '-'} */}
            {`${percent}% ${ofEmission}`}
          </div>
        )}
      </div>

      <div className={` ${alignmentClass} `}>
        <div className={`text-xl font-extrabold ${textColor || 'text-white'}`}>{valuePart}</div>
        {unitPart && (
          <div className={`text-[11px] mt-0.5 uppercase font-light ${textColor || 'text-white'}`} style={{ position: 'relative', bottom: 5 }}>{unitPart}</div>
        )}
        <div className={`text-[11px] uppercase ${textColor || 'text-white'}`}>{label}</div>
      </div>
    </div>
  )
}

function createThumbRenderer(isHorizontal: boolean) {
  return (props: ScrollbarElementProps) => {
    const { elementRef, ...restProps } = props
    const thumbStyle = isHorizontal
      ? {
          width: '35px',
          height: '35px',
          backgroundImage: 'url(ui/thumb-horizontal.svg)',
          position: 'absolute' as const,
          top: '-13px'
        }
      : {
          width: '35px',
          height: '35px',
          backgroundImage: 'url(ui/thumb2.svg)',
          position: 'relative' as const,
          left: '-13.2px'
        }

    return (
      <div
        {...restProps}
        ref={elementRef}
        style={{
          ...restProps.style,
          ...thumbStyle,
          minWidth: '35px',
          minHeight: '35px',
          maxWidth: '35px',
          maxHeight: '35px',
          backgroundSize: '35px 35px',
          backgroundRepeat: 'no-repeat',
          backgroundPosition: 'center',
          backgroundColor: 'rgba(0, 0, 0, 0.1)',
          border: '0.5px solid rgba(255, 255, 255, 0.3)',
          borderRadius: '50%',
          overflow: 'visible',
          display: 'flex',
          opacity: '0.8',
          justifyContent: 'center',
          zIndex: 10
        }} />
    )
  }
}

function createTrackRenderer(isHorizontal: boolean) {
  return (props: ScrollbarElementProps) => {
    const { elementRef, ...restProps } = props
    const trackStyle = isHorizontal
      ? {
          width: '96.5%',
          height: '11px',
          bottom: '4px'
        }
      : {
          width: '10px',
          height: '82.5%',
          marginTop: '27.5px',
          marginRight: typeof window !== 'undefined' && window.innerWidth >= 1024 ? '23px' : '18px'
        }

    return (
      <div
        {...restProps}
        ref={elementRef}
        style={{
          ...restProps.style,
          ...trackStyle,
          borderRadius: '100px',
          overflow: 'visible',
          backgroundColor: 'rgba(0, 0, 0, 0.15)',
          border: '1px solid rgba(255, 255, 255, 0.1)'
        }} />
    )
  }
}

/**
 * Verifica se 100% da população está sem acompanhamento
 */
function isAllPopulationWithoutFollowUp(
  selectedConditions: string[],
  followUp: Record<string, FollowUpDistribution>
): boolean {
  return selectedConditions.every((condition) => {
    const distribution = followUp[condition]
    return distribution?.none === 100
  })
}

/**
 * Calcula emissões para cenário com acompanhamento Point of Care
 */
function calculatePointOfCareEmissions(
  totalPeople: number,
  conditionProducts: ConditionProducts
): number {
  let emissions = 0
  const annualProducts = conditionProducts.annual?.pointOfCare || []

  for (const product of annualProducts) {
    const totalQuantity = totalPeople * product.quantity * FREQUENCY_MULTIPLIERS.annual
    emissions += totalQuantity * product.emissionFactor
  }

  return emissions
}

/**
 * Calcula emissões para cenário com distribuição normal de acompanhamento
 */
function calculateNormalFollowUpEmissions(
  totalPeople: number,
  distribution: FollowUpDistribution,
  examType: 'conventional' | 'pointOfCare',
  conditionProducts: ConditionProducts
): number {
  let emissions = 0
  const percentWithFollowUp = (distribution.annual || 0) + (distribution.semiannual || 0)
  const peopleWithFollowUp = Math.round((totalPeople * percentWithFollowUp) / 100)
  const productType = examType === 'conventional' ? 'conventional' : 'pointOfCare'
  const annualProducts = conditionProducts.annual?.[productType] || []

  for (const product of annualProducts) {
    const totalQuantity = peopleWithFollowUp * product.quantity * FREQUENCY_MULTIPLIERS.annual
    emissions += totalQuantity * product.emissionFactor
  }

  return emissions
}

/**
 * Calcula emissões para hospitalizações (sem acompanhamento)
 * Simula o cenário onde TODAS as pessoas estariam sem acompanhamento
 */
function calculateHospitalizationEmissions(
  totalPeople: number,
  conditionProducts: ConditionProducts
): number {
  let emissions = 0
  // Para o cenário de comparação, simular TODAS as pessoas sem acompanhamento
  const peopleWithoutFollowUp = totalPeople
  const noneProducts = conditionProducts.none?.conventional || []

  for (const product of noneProducts) {
    const totalQuantity = peopleWithoutFollowUp * product.quantity * FREQUENCY_MULTIPLIERS.none
    emissions += totalQuantity * product.emissionFactor
  }

  return emissions
}

export function PopulationStep4() {
  const {
    population,
    results,
    examType,
    updateExamType,
    followUp
  } = usePopulation()
  const { t } = useLanguage()

  // Helper to get sustainability suggestion for exam type
  function getExamTypeSustainabilitySuggestion(type: 'conventional' | 'pointOfCare') {
    // Verificar se a maioria da população está sem acompanhamento
    const selectedConditions = Object.keys(population).filter((condition) =>
      population[condition as keyof typeof population] > 0
    )

    let totalPeople = 0
    let totalWithoutFollowUp = 0

    for (const condition of selectedConditions) {
      const peopleCount = population[condition as keyof typeof population]
      const distribution = followUp[condition as keyof typeof followUp]
      const percentWithoutFollowUp = distribution.none || 0

      totalPeople += peopleCount
      totalWithoutFollowUp += Math.round((peopleCount * percentWithoutFollowUp) / 100)
    }

    // Se mais de 50% da população está sem acompanhamento
    const percentWithoutFollowUp = totalPeople > 0 ? (totalWithoutFollowUp / totalPeople) * 100 : 0

    if (percentWithoutFollowUp > 50) {
      return { description: t('populationSuggestions.sustainabilitySuggestion.description') }
    }

    if (type === 'conventional') {
      return { description: t('suggestions.suggestion04.description') }
    }

    return { description: t('suggestions.suggestion05.description') }
  }

  // Sugestões dinâmicas baseadas nas condições e distribuição de follow-up
  const dynamicSuggestions = useMemo(() => {
    if (!examType) return []

    return getPopulationSuggestions(
      population,
      examType,
      followUp as unknown as Record<string, { none: number, annual: number, semiannual: number }>
    )
  }, [population, examType, followUp])

  // Calcular comparação: Point of Care Anual vs Sem Acompanhamento
  const followUpComparison = useMemo(() => {
    let withFollowUpEmissions = 0
    let withoutFollowUpEmissions = 0

    const selectedConditions = Object.keys(population).filter((condition) =>
      population[condition as keyof typeof population] > 0
    )

    const is100PercentNone = isAllPopulationWithoutFollowUp(
      selectedConditions,
      followUp as unknown as Record<string, FollowUpDistribution>
    )

    for (const condition of selectedConditions) {
      const totalPeople = population[condition as keyof typeof population]
      const distribution = followUp[condition as keyof typeof followUp]
      const conditionProducts = PRODUCTS_BY_CONDITION[condition as keyof typeof PRODUCTS_BY_CONDITION]

      if (!conditionProducts || totalPeople === 0) continue

      // Cenário 1: COM acompanhamento
      if (is100PercentNone) {
        withFollowUpEmissions += calculatePointOfCareEmissions(totalPeople, conditionProducts)
      } else {
        withFollowUpEmissions += calculateNormalFollowUpEmissions(
          totalPeople,
          distribution,
          examType,
          conditionProducts
        )
      }

      // Cenário 2: SEM acompanhamento (Hospitalization)
      withoutFollowUpEmissions += calculateHospitalizationEmissions(
        totalPeople,
        conditionProducts
      )
    }

    const difference = withoutFollowUpEmissions - withFollowUpEmissions
    const percentDifference = withFollowUpEmissions > 0
      ? Math.round((difference / withFollowUpEmissions) * 100)
      : 0

    return {
      withFollowUp: withFollowUpEmissions,
      withoutFollowUp: withoutFollowUpEmissions,
      difference,
      percentDifference: Math.abs(percentDifference)
    }
  }, [population, examType, followUp])

  // Calcular emissões apenas das pessoas COM acompanhamento (excluindo "none")
  const emissionsWithFollowUpOnly = useMemo(() => {
    let emissions = 0
    let emissionsWithoutFollowUp = 0
    let hasAnyWithoutFollowUp = false

    const selectedConditions = Object.keys(population).filter((condition) =>
      population[condition as keyof typeof population] > 0
    )

    for (const condition of selectedConditions) {
      const totalPeople = population[condition as keyof typeof population]
      const distribution = followUp[condition as keyof typeof followUp]
      const conditionProducts = PRODUCTS_BY_CONDITION[condition as keyof typeof PRODUCTS_BY_CONDITION]

      if (!conditionProducts || totalPeople === 0) continue

      // Verificar se há pessoas sem acompanhamento
      const percentWithoutFollowUp = distribution.none || 0
      const peopleWithoutFollowUp = Math.round((totalPeople * percentWithoutFollowUp) / 100)

      if (peopleWithoutFollowUp > 0) {
        hasAnyWithoutFollowUp = true

        // Calcular emissões das pessoas SEM acompanhamento
        const noneProducts = conditionProducts.none?.conventional || []
        for (const product of noneProducts) {
          const totalQuantity = peopleWithoutFollowUp * product.quantity * FREQUENCY_MULTIPLIERS.none
          emissionsWithoutFollowUp += totalQuantity * product.emissionFactor
        }
      }

      // Calcular apenas para pessoas COM acompanhamento (annual + semiannual)
      const percentWithFollowUp = (distribution.annual || 0) + (distribution.semiannual || 0)
      const peopleWithFollowUp = Math.round((totalPeople * percentWithFollowUp) / 100)

      if (peopleWithFollowUp === 0) continue

      const productType = examType === 'conventional' ? 'conventional' : 'pointOfCare'
      const annualProducts = conditionProducts.annual?.[productType] || []

      for (const product of annualProducts) {
        const totalQuantity = peopleWithFollowUp * product.quantity * FREQUENCY_MULTIPLIERS.annual
        emissions += totalQuantity * product.emissionFactor
      }
    }

    return {
      emissions,
      emissionsWithoutFollowUp,
      hasAnyWithoutFollowUp
    }
  }, [population, examType, followUp])

  // Calcular comparação: Convencional Anual vs Point of Care Anual
  const examTypeComparison = useMemo(() => {
    let conventionalEmissions = 0 // Convencional Anual
    let pointOfCareEmissions = 0 // Point of Care Anual

    const selectedConditions = Object.keys(population).filter((condition) =>
      population[condition as keyof typeof population] > 0
    )

    for (const condition of selectedConditions) {
      const totalPeople = population[condition as keyof typeof population]
      const conditionProducts = PRODUCTS_BY_CONDITION[condition as keyof typeof PRODUCTS_BY_CONDITION]

      if (!conditionProducts || totalPeople === 0) continue

      // Cenário 1: Convencional Anual
      const annualConvProducts = conditionProducts.annual?.conventional || []
      for (const product of annualConvProducts) {
        const totalQuantity = totalPeople * product.quantity * FREQUENCY_MULTIPLIERS.annual
        conventionalEmissions += totalQuantity * product.emissionFactor
      }

      // Cenário 2: Point of Care Anual
      const annualPocProducts = conditionProducts.annual?.pointOfCare || []
      for (const product of annualPocProducts) {
        const totalQuantity = totalPeople * product.quantity * FREQUENCY_MULTIPLIERS.annual
        pointOfCareEmissions += totalQuantity * product.emissionFactor
      }
    }

    const totalForComparison = conventionalEmissions + pointOfCareEmissions
    const conventionalPercent = totalForComparison > 0 ? Math.round((conventionalEmissions / totalForComparison) * 100) : 0
    const pointOfCarePercent = totalForComparison > 0 ? Math.round((pointOfCareEmissions / totalForComparison) * 100) : 0

    return {
      conventional: conventionalEmissions,
      pointOfCare: pointOfCareEmissions,
      conventionalPercent,
      pointOfCarePercent
    }
  }, [population])

  const productsByConditionAndFollowUp = useMemo(() => {
    const addProductsOfType = (
      products: AutoGeneratedProduct[],
      conditionProducts: ConditionProducts,
      followUpType: string,
      examType: ExamType,
      condition: string,
      productType: 'conventional' | 'pointOfCare',
      peopleCount: number
    ) => {
      const scenarioProducts = conditionProducts[followUpType]?.[productType]
      if (!scenarioProducts) return

      for (let index = 0; index < scenarioProducts.length; index++) {
        const product = scenarioProducts[index]
        const baseQuantity = product.quantity
        const totalQuantity = baseQuantity * peopleCount

        products.push({
          id: `${condition}_${followUpType}_${examType}_${index}`,
          ...product,
          quantity: totalQuantity,
          category: product.category,
          condition,
          followUpType,
          examType
        })
      }
    }

    if (!examType) return { conventional: {}, pointOfCare: {} }

    const result = {
      conventional: {} as Record<string, Record<string, AutoGeneratedProduct[]>>,
      pointOfCare: {} as Record<string, Record<string, AutoGeneratedProduct[]>>
    }

    const selectedConditions = Object.keys(population).filter((condition) =>
      population[condition as keyof typeof population] > 0
    )

    const followUpTypes: string[] = ['none', 'annual', 'semiannual']

    for (const condition of selectedConditions) {
      const totalPopulation = population[condition as keyof typeof population]
      const distribution = followUp[condition as keyof typeof followUp]

      result.conventional[condition] = {
        none: [],
        annual: [],
        semiannual: []
      }

      result.pointOfCare[condition] = {
        none: [],
        annual: [],
        semiannual: []
      }

      const conditionProducts = PRODUCTS_BY_CONDITION[condition as keyof typeof PRODUCTS_BY_CONDITION]
      if (!conditionProducts) continue

      for (const followUpType of followUpTypes) {
        const percentage = distribution[followUpType as keyof typeof distribution]
        const peopleCount = Math.round((totalPopulation * percentage) / 100)

        const productsConventional: AutoGeneratedProduct[] = []
        const productsPointOfCare: AutoGeneratedProduct[] = []

        if (peopleCount > 0) {
          addProductsOfType(productsConventional, conditionProducts, followUpType, examType, condition, 'conventional', peopleCount)
          addProductsOfType(productsPointOfCare, conditionProducts, followUpType, examType, condition, 'pointOfCare', peopleCount)
        }

        result.conventional[condition][followUpType] = productsConventional
        result.pointOfCare[condition][followUpType] = productsPointOfCare
      }
    }

    return result
  }, [examType, population, followUp])

  // Verificar se 100% da população está sem acompanhamento
  const is100PercentWithoutFollowUp = useMemo(() => {
    const selectedConditions = Object.keys(population).filter((condition) =>
      population[condition as keyof typeof population] > 0
    )

    if (selectedConditions.length === 0) return false

    return selectedConditions.every((condition) => {
      const distribution = followUp[condition as keyof typeof followUp]
      return distribution.none === 100
    })
  }, [population, followUp])

  // Garantir que conventional está selecionado quando 100% sem acompanhamento
  useMemo(() => {
    if (is100PercentWithoutFollowUp && examType !== 'conventional') {
      updateExamType('conventional')
    }
  }, [is100PercentWithoutFollowUp, examType, updateExamType])

  if (!results) return null

  const totalPopulation = Object.values(population).reduce((sum, val) => sum + val, 0)

  const handleExamTypeChange = (type: ExamType) => {
    updateExamType(type)
  }

  const formatEmissions = (kgValue: number, tonDecimals: number = 3, showCarbonUnit = true): { value: string, unit: string } => {
    const carbonUnit = showCarbonUnit ? ' CO₂e' : ''

    if (kgValue >= 1000) {
      const tons = kgValue / 1000
      return {
        value: tons.toFixed(tonDecimals),
        unit: `t${carbonUnit}`
      }
    }
    if (kgValue < 1) {
      const grams = kgValue * 1000
      return {
        value: grams.toFixed(3),
        unit: `g${carbonUnit}`
      }
    }
    return {
      value: kgValue.toFixed(2),
      unit: `kg${carbonUnit}`
    }
  }

  const getCurrentProducts = () => {
    const allProducts: AutoGeneratedProduct[] = []
    const selectedConditions = Object.keys(population).filter((condition) =>
      population[condition as keyof typeof population] > 0
    )

    const followUpTypes: string[] = ['annual', 'semiannual', 'none']

    for (const condition of selectedConditions) {
      const examData = examType === 'conventional'
        ? productsByConditionAndFollowUp.conventional[condition]
        : productsByConditionAndFollowUp.pointOfCare[condition]

      if (!examData) continue

      for (const followUpType of followUpTypes) {
        const products = examData[followUpType]
        if (products) {
          // Aplicar multiplicador de frequência
          const frequencyMultiplier = FREQUENCY_MULTIPLIERS[followUpType as keyof typeof FREQUENCY_MULTIPLIERS]
          const adjustedProducts = products.map((p) => ({
            ...p,
            quantity: p.quantity * frequencyMultiplier
          }))
          allProducts.push(...adjustedProducts)
        }
      }
    }

    return allProducts
  }

  const getConditionsTitle = () => {
    const activeConditions = Object.keys(population).filter((condition) =>
      population[condition as keyof typeof population] > 0
    )
    return activeConditions.map((condition) => {
      const labelMap: Record<string, string> = {
        lowerBackPain: t('step1.lowerBackPain'),
        hypertension: t('step1.hypertension'),
        diabetes: t('step1.diabetes'),
        overweight: t('step1.overweight'),
        noChronicConditions: t('step1.noChronicConditions')
      }
      return labelMap[condition] || condition
    }).join(', ')
  }
  const followUpType = 'annual'

  const conventionalTextColor = examType === 'conventional' ? 'text-red-400' : 'text-white/70'
  const pointOfCareTextColor = examType === 'pointOfCare' ? 'text-green-400' : 'text-white/70'

  // Helper para obter o texto do label do cenário com acompanhamento
  const getFollowUpScenarioLabel = () => {
    if (is100PercentWithoutFollowUp) {
      return `${t('step3.pointOfCare')} 100% ${t('step1.annual') ?? 'Anual'}`
    }
    const examTypeLabel = examType === 'conventional' ? t('step3.conventional') : t('step3.pointOfCare')
    return `${examTypeLabel} 100% ${t('step1.annual') ?? 'Anual'}`
  }

  const renderExamTypeButton = (
    type: 'conventional' | 'pointOfCare',
    imageSrc: string,
    imagePosition: 'left' | 'right'
  ) => {
    const isSelected = examType === type
    const label = type === 'conventional' ? t('conventional') : t('pointOfCare')

    return (
      <button
        type="button"
        onClick={() => handleExamTypeChange(type)}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault()
            handleExamTypeChange(type)
          }
        }}
        className={`
          cursor-pointer flex flex-row items-center
          ${imagePosition === 'right' ? 'justify-end' : 'justify-start'}
          ${isSelected ? 'scale-none' : 'hover:scale-105 active:scale-95'}
        `}>

        <div
          className={`
            rounded-full transition-colors
            ${isSelected
              ? 'border-[#52AE32] ring-2 ring-[#52AE32]'
              : 'border-white/20 hover:border-white/30'
            }
          `}>
          <div className="glass-container rounded-full!">
            <div className="glass-filter"></div>
            <div className="glass-overlay"></div>
            <div className="glass-specular"></div>
            <div
              className={`
                glass-content flex-row! gap-0! p-0!
                ${isSelected ? 'bg-black/40' : 'text-white/60!'}
                ${imagePosition === 'right' ? 'flex-row-reverse! pl-4!' : 'pr-4!'}
              `}>
              <img
                src={imageSrc}
                alt=""
                className={`
                  z-10 w-10 h-10 lg:w-16 lg:h-16
                  ${!isSelected && 'opacity-50'}
                  ${imagePosition === 'right' && '-ml-2'}
                `} />
              <p className="my-2.5 text-xs font-light">
                {label}
              </p>
            </div>
          </div>
        </div>
      </button>
    )
  }

  return (
    <div className="mt-10.5 lg:mt-13.5 mb-0 lg:mb-4 relative h-[calc(min(100dvh,950px)-15rem)] lg:h-[calc(min(100dvh,950px)-19.25rem)] min-h-100 w-full">
      <SectionHeader
        title={t('step4.population.completeAnalysisTitle')}
        subtitle=" "
        className="absolute -mt-10" />

      {/* Exam Type Selection - Ocultar se 100% sem acompanhamento */}
      {!is100PercentWithoutFollowUp && (
        <div className="absolute top-0 flex justify-center gap-4 mb-4 transform -translate-x-1/2 -translate-y-1/2 select-none left-1/2 z-15">
          {renderExamTypeButton('conventional', '/ui/icon-conventional.png', 'right')}
          {renderExamTypeButton('pointOfCare', '/ui/icon-pointofcare.png', 'left')}
        </div>
      )}

      <div className="glass-container border-3 border-[#52AE32] rounded-[35px]! h-full">
        <div className="glass-filter rounded-4xl!"></div>
        <div className="glass-overlay rounded-4xl!"></div>
        <div className="glass-specular rounded-4xl!"></div>
        <div className="glass-content p-0! rounded-sm! inset-shadow-bolder h-full">
          <Scrollbar
            thumbYProps={{ renderer: createThumbRenderer(false) }}
            trackYProps={{ renderer: createTrackRenderer(false) }}
            minimalThumbYSize={35}
            maximalThumbYSize={35}
            disableTrackYWidthCompensation={true}
            style={{ height: '100%', width: '100%' }}>
            <div className="h-full pl-4 pr-12 pt-6 pb-10 lg:px-14 lg:pt-15 min-w-fit">
              {/* Mobile: Sustainability Recommendation at Top */}
              <div className="block mb-6 lg:hidden">
                <div className="glass-container w-full gap-0!">
                  {/* <div className="glass-filter"></div> */}
                  <div className="glass-overlay"></div>
                  <div className="glass-specular"></div>
                  <div className="w-full glass-content">
                    <div className="flex items-center justify-around w-full min-h-40 py-4 px-2">
                      <div className="flex flex-col flex-1 min-w-0">
                        <div className="z-10 w-full p-2 font-bold text-left text-white uppercase font-krona-one text-md">
                          {t('step5.recommendations')}
                        </div>
                        <div className="flex flex-col p-2 overflow-y-auto scrollbar-dark">
                          <p className="text-[12px] text-white text-left leading-relaxed">
                            {getExamTypeSustainabilitySuggestion(examType).description}
                          </p>
                        </div>
                      </div>
                      <img src="ui/suggestions/icon-peace.png" alt="World Icon" className="mt-3 w-30" />
                    </div>
                  </div>
                </div>
              </div>

              {/* Grid Principal: Responsivo - 3 colunas em desktop, 1 coluna em mobile */}
              <div className="grid gap-6 h-full xl:grid-cols-[minmax(220px,4fr)_minmax(320px,7fr)_minmax(400px,9fr)] lg:grid-cols-[minmax(220px,4fr)_minmax(300px,7fr)_minmax(350px,9fr)] md:grid-cols-[1fr_2fr] sm:grid-cols-[1fr_2fr] grid-cols-1">
                {/* COLUNA 1 (Esquerda): Cards de Métricas */}
                <div className="flex flex-col justify-between order-1 gap-6 ">
                  <StatCard
                    value={String(totalPopulation).padStart(2, '0')}
                    icon="/ui/icon-group.png"
                    label={t('step4.totalPopulation')} />

                  <StatCard
                    value={String(results.products.reduce((sum, p) => {
                      const frequencyMultiplier = FREQUENCY_MULTIPLIERS[p.followUpType]
                      return sum + (p.totalQuantity * frequencyMultiplier)
                    }, 0)).padStart(2, '0')}
                    icon="/ui/icon-products.png"
                    label={t('step4.productsGenerated')} />

                  <StatCard
                    value={formatEmissions(followUpComparison.difference).value}
                    icon="/ui/icon-hospital.png"
                    size="10px"
                    label={t('step5.emissionsByHospitalizations')}
                    showUnity
                    unit={formatEmissions(followUpComparison.difference).unit} />

                  <StatCard
                    value={String(Math.round(followUpComparison.difference / 24)).padStart(2, '0')}
                    icon="/ui/icon-tree.png"
                    label={t('step5.equivalentTrees')} />
                </div>

                {/* COLUNA 2 (Meio): Cards de Comparação */}
                <div className="flex flex-col order-2 gap-6 min-w-0">
                  {/* Total Emissions Card */}
                  <div className="glass-container rounded-2xl w-full">
                    {/* <div className="glass-filter"></div> */}
                    <div className="glass-overlay"></div>
                    <div className="glass-specular"></div>
                    <div className="glass-content py-0 lg:py-10! flex! gap-0! flex-row!">
                      <img src="ui/icon-carbon.png" alt="Carbon Icon" className="w-15 lg:w-20 shrink-0" />
                      <div className="glass-container rounded-2xl flex-1 min-w-0">
                        {/* <div className="glass-filter"></div> */}
                        <div className="glass-overlay"></div>
                        <div className="glass-specular"></div>
                        <div className="glass-content py-2! lg:py-5! px-12.5! bg-black/20">
                          <div className="flex flex-col text-center">
                            <p className="text-xl lg:text-3xl font-extrabold! font-kreon">
                              {`
                                ${formatEmissions(results.totalEmissions, 2).value}
                                ${formatEmissions(results.totalEmissions, 2).unit}
                              `}
                            </p>
                            <p className="font-kreon text-sm lg:text-lg font-bold! text-[#52AE32]">
                              {t('step4.totalEmissions')}
                            </p>
                            {emissionsWithFollowUpOnly.hasAnyWithoutFollowUp && (
                              <div className="text-xs mt-2 text-[10px]">
                                <p className="text-white/60">
                                  {`Com acompanhamento: `}
                                  <span className="text-white">
                                    {`
                                      ${formatEmissions(emissionsWithFollowUpOnly.emissions).value}
                                      ${formatEmissions(emissionsWithFollowUpOnly.emissions, 3, false).unit}
                                    `}
                                  </span>
                                </p>
                                <p className="text-white/60">
                                  {`Sem acompanhamento: `}
                                  <span className="text-white">
                                    {`
                                      ${formatEmissions(emissionsWithFollowUpOnly.emissionsWithoutFollowUp).value}
                                      ${formatEmissions(emissionsWithFollowUpOnly.emissionsWithoutFollowUp, 3, false).unit}
                                    `}
                                  </span>
                                </p>
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Exam Type Comparison */}
                  <div className="glass-container w-full min-w-0">
                    {/* <div className="glass-filter"></div> */}
                    <div className="glass-overlay"></div>
                    <div className="glass-specular"></div>
                    <div className="glass-content px-0! gap-0! lg:gap-4!">
                      <div className="flex flex-row items-center border-b border-white/50 w-[80%] gap-1">
                        {/* <img src="ui/icon-chart.png" alt="" className="w-8" /> */}
                        <div>
                          <h3 className="text-xs font-light text-white uppercase">
                            {t('step4.examComparison')}
                          </h3>
                          <p className="-mt-0.5 text-[9px] text-left text-white/80">
                            {t('step4.population.annualDistributionNote')}
                          </p>
                        </div>
                      </div>

                      <div className="flex flex-row items-center justify-between w-full mt-4 mb-2">
                        {/* Convencional */}
                        <div className="flex flex-col flex-1 items-right">
                          <PercentBadge
                            percent={examTypeComparison.conventionalPercent}
                            emissionValue={`${formatEmissions(examTypeComparison.conventional).value} ${formatEmissions(examTypeComparison.conventional).unit}`}
                            label={t('conventional')}
                            color="#DC0B0B"
                            side="conventional"
                            textColor={conventionalTextColor}
                            examType={examType}
                            ofEmission={t('step5.ofEmission')} />
                        </div>

                        {/* Percentual no meio: circular progress */}
                        <div className="flex items-center justify-center px-2">
                          <CircularProgress
                            percent={examType === 'conventional' ? examTypeComparison.conventionalPercent : examTypeComparison.pointOfCarePercent}
                            size={100}
                            strokeWidth={10}
                            color={examType === 'conventional' ? '#DC0B0B' : '#52AE32'}
                            isPointOfCare={examType === 'pointOfCare'} />
                        </div>

                        {/* Point of Care */}
                        <div className="flex flex-col flex-1 items-left">
                          <PercentBadge
                            percent={examTypeComparison.pointOfCarePercent}
                            emissionValue={`${formatEmissions(examTypeComparison.pointOfCare).value} ${formatEmissions(examTypeComparison.pointOfCare).unit}`}
                            label={t('pointOfCare')}
                            color="#52ae32"
                            side="pointOfCare"
                            textColor={pointOfCareTextColor}
                            examType={examType}
                            ofEmission={t('step5.ofEmission')} />
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Follow-up Comparison */}
                  <ComparisonCard
                    title={`${t('step5.followUpImpact')}`}
                    subtitle={t('step4.population.annualDistributionNote')}
                    icon="ui/icon-arrow.png">
                    <div className="flex flex-wrap lg:flex-nowrap justify-between gap-2 lg:gap-4 w-full">
                      <div className="flex flex-col flex-1 min-w-30 items-center gap-2">
                        <span className="text-xs font-semibold text-center text-green-200">
                          <span className="text-xl lg:text-2xl">
                            {formatEmissions(followUpComparison.withFollowUp).value}
                          </span>
                          <br />
                          {formatEmissions(followUpComparison.withFollowUp).unit}
                        </span>
                        <img src="/ui/hospital_2.png" alt="With Follow-up" className="h-10 w-7 lg:w-13 lg:h-16 hospital-image" />
                        <div className="flex flex-col justify-center min-h-14.5 w-full px-1 lg:px-4 py-2 bg-[#0B79DC] rounded-[40px] text-white/90 text-center text-[10px] lg:text-sm leading-tight wrap-break-word hyphens-auto">
                          {t('step5.withFollowUp')}
                          <br />
                          <span className="text-[9px] block">
                            {getFollowUpScenarioLabel()}
                          </span>
                        </div>
                      </div>
                      <div className="flex flex-col flex-1 min-w-30 items-center gap-2">
                        <span className="text-xs font-semibold text-center text-red-200">
                          <span className="text-xl lg:text-2xl">
                            {formatEmissions(followUpComparison.withoutFollowUp).value}
                          </span>
                          <br />
                          {formatEmissions(followUpComparison.withoutFollowUp).unit}
                        </span>
                        <img src="/ui/hospital_1.png" alt="Without Follow-up" className="h-10 w-7 lg:w-13 lg:h-16 hospital-image" />
                        <div className="flex flex-col justify-center min-h-14.5 w-full px-1 lg:px-4 py-2 bg-[#DC0B0B] rounded-[40px] text-white/90 text-center text-[10px] lg:text-sm leading-tight wrap-break-word hyphens-auto">
                          <p>{t('step5.withoutFollowUp')}</p>
                        </div>
                      </div>
                    </div>
                    {/*
                    <div className="flex text-[#3AD0F5] items-center gap-2 text-sm">
                      {t('step5.different')}
                      <hr className="w-30 h-[0.1px] border-[#00CCFF]/40 border-b-[0.1px]" />
                      <span className="text-2xl font-bold">
                        {`${followUpComparison.percentDifference}%`}
                      </span>
                    </div>
                    */}
                  </ComparisonCard>
                </div>

                {/* COLUNA 3 (Direita): Grid com 2 Linhas (Sustentabilidade | Tabela) */}
                <div className="grid grid-rows-[auto_1fr] gap-6 lg:order-3 lg:col-span-1 order-3 col-span-2">
                  {/* Exam Type Sustainability Suggestion - Hidden on mobile, shown on desktop */}
                  <div className="hidden! lg:block! glass-container w-full gap-0!">
                    {/* <div className="glass-filter"></div> */}
                    <div className="glass-overlay"></div>
                    <div className="glass-specular"></div>
                    <div className="glass-content w-full!">
                      <div className="flex items-center justify-around w-full min-h-40 py-4 px-2">
                        <div className="flex flex-col flex-1 min-w-0">
                          <div className="z-10 w-full p-2 font-bold text-left text-white uppercase font-krona-one text-md">
                            {t('step5.recommendations')}
                          </div>
                          <div className="flex flex-col p-2 overflow-y-auto scrollbar-dark">
                            <p className="text-[12px] text-white text-left leading-relaxed">
                              {getExamTypeSustainabilitySuggestion(examType).description}
                            </p>
                          </div>
                        </div>
                        <img src="ui/suggestions/icon-peace.png" alt="World Icon" className="mt-3 w-30" />
                      </div>
                    </div>
                  </div>

                  {/* Materials Table */}
                  <div className="glass-container w-full min-h-75 lg:min-h-0">
                    {/* <div className="glass-filter"></div> */}
                    <div className="glass-overlay"></div>
                    <div className="glass-specular"></div>
                    <div className="glass-content p-0! w-full h-full">
                      <ProductsTable
                        products={getCurrentProducts()}
                        config={{
                          examType,
                          followUpType,
                          title: getConditionsTitle(),
                          showFollowUpTypeColumn: false,
                          considerFrequencyMultiplier: false
                        }} />
                    </div>
                  </div>
                </div>
              </div>

              {/* Suggestions - Full Width Below All Columns */}
              <div className="glass-container flex-col h-[272.5px] mt-6 w-full">
                <div className="font-krona-one bg-[#52AE32] text-white uppercase z-10 w-full p-2 font-bold text-left pl-8 text-md">
                  {t('step5.reductionSuggestions')}
                </div>
                {/* <div className="glass-filter"></div> */}
                <div className="glass-overlay"></div>
                <div className="glass-specular"></div>
                <div className="glass-content w-full mt-2.5">
                  <Scrollbar
                    minimalThumbXSize={35}
                    maximalThumbXSize={35}
                    disableTrackYWidthCompensation={true}
                    disableTrackXWidthCompensation={true}
                    style={{ width: '100%', height: '100%' }}
                    thumbXProps={{ renderer: createThumbRenderer(true) }}
                    trackXProps={{ renderer: createTrackRenderer(true) }}>
                    <div className="flex flex-row gap-x-6">
                      {dynamicSuggestions.map((suggestion) => {
                        const title = suggestion.titleKey ? t(suggestion.titleKey) : ''
                        const description = suggestion.descriptionKey ? t(suggestion.descriptionKey) : ''
                        const subDescriptionText = suggestion.subDescriptionKey ? t(suggestion.subDescriptionKey) : ''
                        const hasSubDescription = subDescriptionText && subDescriptionText !== suggestion.subDescriptionKey

                        return (
                          <div key={`population-${suggestion.translationKey}`} className="min-w-50 h-20">
                            <div className="glass-container">
                              {/* <div className="glass-filter"></div> */}
                              <div className="glass-overlay"></div>
                              <div className="glass-specular"></div>
                              <div className="glass-content p-0! py-6! px-5! h-39.5">
                                <div className="flex flex-col h-28.75 overflow-y-auto scrollbar-dark pr-2">
                                  {title && (
                                    <div className="flex items-center gap-2 mb-2">
                                      <p className="text-[11px] text-[#52AE32] font-semibold">
                                        {title}
                                      </p>
                                    </div>
                                  )}
                                  {description && (
                                    <p className="text-[12px] text-white text-left leading-relaxed mb-0.5">
                                      {description}
                                    </p>
                                  )}
                                  {hasSubDescription && (
                                    <p className="text-[11px] text-green-300/90 text-left leading-relaxed border-l-2 border-green-400/50 pl-2">
                                      {subDescriptionText}
                                    </p>
                                  )}
                                </div>
                                <div>
                                  <div className="absolute -bottom-4.5 -right-2.5">
                                    <img src={suggestion.iconPath} alt={title} className="w-25 opacity-30" />
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        )
                      })}
                    </div>
                  </Scrollbar>
                </div>
              </div>
            </div>
          </Scrollbar>
        </div>
      </div>
    </div>
  )
}
