import type { ElementPropsWithElementRef, ScrollState } from 'react-scrollbars-custom/dist/types/types'
import type { AutoGeneratedProduct } from '@/types/patient'
import type { ExamType, FollowUpType } from '@/types/shared'
import { useMemo } from 'react'
import { Scrollbar } from 'react-scrollbars-custom'
import AjudinhaPopover from '@/components/ui/ajudinha-popover'
import SectionHeader from '@/components/ui/section-header'
import { FREQUENCY_MULTIPLIERS } from '@/constants/emissions'
import { getFollowUpConfig, getProductName, PRODUCTS_BY_CONDITION } from '@/constants/healthcareData'
import useLanguage from '@/hooks/useLanguage'
import { usePopulation } from '@/hooks/usePopulation'

type ScrollbarElementProps = ElementPropsWithElementRef<HTMLDivElement>

export function PopulationStep3() {
  const { population, followUp, examType, updateExamType } = usePopulation()
  const { t, language } = useLanguage()

  // Obter configuração de follow-up traduzida
  const followUpConfig = useMemo(() => getFollowUpConfig(language), [language])

  const handleScroll = (_event: React.UIEvent<HTMLDivElement> | ScrollState, examTypeToSelect: ExamType) => {
    if (examTypeToSelect !== examType) updateExamType(examTypeToSelect)
  }

  // Usar produtos e configurações centralizados
  const productsByCondition = PRODUCTS_BY_CONDITION

  interface ProductsByScenario {
    conventional?: Array<{
      name: string
      category: string
      emissionFactor: number
      quantity: number
    }>
    pointOfCare?: Array<{
      name: string
      category: string
      emissionFactor: number
      quantity: number
    }>
  }

  type ConditionProducts = Record<string, ProductsByScenario>

  /**
   * Gera produtos organizados por condição, tipo de acompanhamento e tipo de exame
   * Calcula quantidades baseadas na população e distribuição de follow-up
   */
  const productsByConditionAndFollowUp = useMemo(() => {
    /**
     * Adiciona produtos de um tipo específico ao array de produtos
     */
    const addProductsOfType = (
      products: AutoGeneratedProduct[],
      conditionProducts: ConditionProducts,
      followUpType: FollowUpType,
      examType: ExamType,
      condition: string,
      productType: 'conventional' | 'pointOfCare',
      peopleCount: number
    ) => {
      const scenarioProducts = conditionProducts[followUpType]?.[productType]
      if (!scenarioProducts) return

      for (let index = 0; index < scenarioProducts.length; index++) {
        const product = scenarioProducts[index]
        // Calcular quantidade baseada no número de pessoas
        const baseQuantity = product.quantity
        const totalQuantity = baseQuantity * peopleCount

        products.push({
          id: `${condition}_${followUpType}_${examType}_${index}`,
          ...product,
          quantity: totalQuantity,
          category: product.category as 'material' | 'service',
          condition,
          followUpType,
          examType
        })
      }
    }

    if (!examType) return { conventional: {}, pointOfCare: {} }

    const result = {
      conventional: {} as Record<string, Record<FollowUpType, AutoGeneratedProduct[]>>,
      pointOfCare: {} as Record<string, Record<FollowUpType, AutoGeneratedProduct[]>>
    }

    const selectedConditions = Object.keys(population).filter((condition) =>
      population[condition as keyof typeof population] > 0
    )

    const followUpTypes: FollowUpType[] = ['none', 'annual', 'semiannual']

    // Para cada condição, gerar produtos para cada tipo de acompanhamento
    for (const condition of selectedConditions) {
      const totalPopulation = population[condition as keyof typeof population]
      const distribution = followUp[condition as keyof typeof followUp]

      result.conventional[condition] = {
        none: [],
        annual: [],
        semiannual: []
      }

      result.pointOfCare[condition] = {
        none: [],
        annual: [],
        semiannual: []
      }

      const conditionProducts = productsByCondition[condition as keyof typeof productsByCondition]
      if (!conditionProducts) continue

      for (const followUpType of followUpTypes) {
        // Calcular número de pessoas para este tipo de acompanhamento
        const percentage = distribution[followUpType]
        const peopleCount = Math.round((totalPopulation * percentage) / 100)

        // Sempre criar arrays, mesmo se peopleCount for 0 (para mostrar tabelas vazias)
        const productsConventional: AutoGeneratedProduct[] = []
        const productsPointOfCare: AutoGeneratedProduct[] = []

        // Só adicionar produtos se houver pessoas
        if (peopleCount > 0) {
          // Adicionar produtos conventional
          addProductsOfType(productsConventional, conditionProducts, followUpType, examType, condition, 'conventional', peopleCount)

          // Adicionar produtos pointOfCare
          addProductsOfType(productsPointOfCare, conditionProducts, followUpType, examType, condition, 'pointOfCare', peopleCount)
        }

        result.conventional[condition][followUpType] = productsConventional
        result.pointOfCare[condition][followUpType] = productsPointOfCare
      }
    }

    return result
  }, [examType, population, productsByCondition, followUp])

  // Obter condições ativas
  const activeConditions = Object.keys(population).filter((condition) =>
    population[condition as keyof typeof population] > 0
  )

  // Mapeamento de labels de doenças com tradução dinâmica
  const getDiseaseLabel = (disease: string): string => {
    const labelMap: Record<string, string> = {
      lowerBackPain: t('step1.lowerBackPain'),
      hypertension: t('step1.hypertension'),
      diabetes: t('step1.diabetes'),
      overweight: t('step1.overweight'),
      noChronicConditions: t('step1.noChronicConditions')
    }
    return labelMap[disease] || disease
  }

  const renderExamTypeButton = (
    type: ExamType,
    imageSrc: string,
    imagePosition: 'left' | 'right'
  ) => {
    const isSelected = examType === type
    const label = type === 'conventional' ? t('step3.conventional') : t('step3.pointOfCare')

    return (
      <button
        type="button"
        onClick={() => updateExamType(type)}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault()
            updateExamType(type)
          }
        }}
        className={`
          cursor-pointer flex flex-row items-center
          ${imagePosition === 'right' ? 'justify-end' : 'justify-start'}
          ${isSelected ? 'scale-none' : 'hover:scale-105 active:scale-95'}
        `}>
        <div
          className={`
            rounded-full transition-colors
            ${isSelected
              ? 'border-[#52AE32] ring-2 ring-[#52AE32]'
              : 'border-white/20 hover:border-white/30'
            }
          `}>
          <div className="glass-container rounded-full!">
            <div className="glass-filter"></div>
            <div className="glass-overlay"></div>
            <div className="glass-specular"></div>
            <div className={`glass-content bg-black/40 flex-row! gap-0! p-0! ${imagePosition === 'right' ? 'flex-row-reverse! pl-4!' : 'pr-4!'}`}>
              <img src={imageSrc} alt="" className={`z-10 w-10 lg:w-16 h-10 lg:h-16 ${imagePosition === 'right' && '-ml-2'}`} />
              <p className="my-2.5 text-xs font-light">
                {label}
              </p>
            </div>
          </div>
        </div>
      </button>
    )
  }

  /**
   * Renderiza tabela de produtos para uma condição específica e tipo de acompanhamento
   */
  const renderProductsTable = (
    condition: string,
    followUpType: FollowUpType,
    products: AutoGeneratedProduct[],
    key: string
  ) => {
    // Se não houver produtos ou pessoas, não renderizar
    if (products.length === 0 || followUpType === 'none') return null

    const distribution = followUp[condition as keyof typeof followUp]
    const totalPopulation = population[condition as keyof typeof population]
    const percentage = distribution[followUpType]
    const peopleCount = Math.round((totalPopulation * percentage) / 100)

    if (peopleCount === 0) return null

    // Aplicar multiplicador de frequência (annual / semiannual) para quantidade e emissões finais
    const frequencyMultiplier = FREQUENCY_MULTIPLIERS[followUpType]
    // Quantidade exibida considera frequência (ex: semiannual = 2 vezes por ano)
    // product.quantity armazenado como quantidade por visita (peopleCount * baseQuantity),
    // então multiplicamos aqui para obter a quantidade anual/total mostrada na tabela
    const quantities = products.map((p) => p.quantity * frequencyMultiplier)
    const hasKgEmissions = products.some((p, i) => (p.emissionFactor * quantities[i]) >= 1)
    const emissionUnit = hasKgEmissions ? 'kg CO\u2082e' : 'g CO\u2082e'
    const productsQuantity = quantities.reduce((acc, value) => acc + value, 0)

    if (productsQuantity === 0) return null

    // Calcular emissões totais
    const totalEmissions = products.reduce((acc, product) => {
      const quantityDisplayed = product.quantity * frequencyMultiplier
      const finalEmissions = product.emissionFactor * quantityDisplayed
      return acc + finalEmissions
    }, 0)
    const totalEmissionsDisplay = hasKgEmissions ? totalEmissions.toFixed(2) : (totalEmissions * 1000).toFixed(2)

    // Ordenar produtos: primeiro por emissão (maior para menor), depois por quantidade (maior para menor)
    const sortedProducts = [...products].sort((a, b) => {
      const emissionsA = a.emissionFactor * (a.quantity * frequencyMultiplier)
      const emissionsB = b.emissionFactor * (b.quantity * frequencyMultiplier)
      const quantityA = a.quantity * frequencyMultiplier
      const quantityB = b.quantity * frequencyMultiplier

      // Se as emissões forem diferentes, ordenar por emissão
      if (emissionsB !== emissionsA) {
        return emissionsB - emissionsA
      }
      // Se as emissões forem iguais, ordenar por quantidade
      return quantityB - quantityA
    })

    return (
      <div key={key}>
        <div className="flex items-center justify-center w-full text-left bg-black/30 py-0.5 mb-1 gap-6">
          <h4 className="text-xs font-medium text-white">
            {getDiseaseLabel(condition)}
          </h4>
          <p className="text-xs rounded text-white/60">
            {` ${followUpConfig[followUpType]?.text}`}
          </p>
          <p className="text-xs text-white/40">
            {`${peopleCount} / ${totalPopulation} ${peopleCount === 1 ? t('step3.population.person') : t('step3.population.people')} - ${percentage.toFixed(0)}%`}
          </p>
          <p className="text-xs text-white/40">
            {`${productsQuantity} ${productsQuantity > 1 ? t('step3.population.products') : t('step3.population.product')}`}
          </p>
          <p className="text-xs text-white/25">
            {`${t('step3.population.final')}: ${totalEmissionsDisplay} ${emissionUnit}`}
          </p>
        </div>

        <div className="mt-1 overflow-x-auto">
          <table className="w-full">
            <thead className="border-white border-b">
              <tr>
                <th className="text-xs w-[38%] pb-1 font-light text-left uppercase text-white">
                  {t('table.product')}
                </th>
                <th className="text-xs w-[12%] pb-1 font-light text-center uppercase text-white">
                  {t('table.quantity')}
                </th>
                <th className="pb-1 text-xs font-light text-center text-white">
                  <span className="uppercase">
                    {t('table.total')}
                  </span>
                  <span>
                    <br />
                    {emissionUnit}
                  </span>
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/10">
              {sortedProducts.map((product, index) => {
                const quantityDisplayed = product.quantity * frequencyMultiplier
                const finalEmissions = product.emissionFactor * quantityDisplayed
                const emissionValue = hasKgEmissions ? finalEmissions : finalEmissions * 1000

                return (
                  <tr key={`${product.id}-${index + 1}`} className="hover:bg-white/5">
                    <td className="py-3 text-xs font-light text-left text-white">
                      {getProductName(product.name, language)}
                    </td>
                    <td className="py-2 text-xs text-center text-white">
                      {`${quantityDisplayed} ${product.category === 'material' ? 'und' : ''}`}
                    </td>
                    <td className="py-2 text-xs font-bold text-[#C8FF3C] text-center">
                      {emissionValue.toFixed(3)}
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      </div>
    )
  }

  /**
   * Consolida todos os produtos de todas as condições para um tipo de exame
   * Soma quantidades de produtos com mesmo nome/categoria
   */
  const renderConditionTables = (condition: string, examTypeToRender: ExamType, key: string) => {
    const examData = examTypeToRender === 'conventional'
      ? productsByConditionAndFollowUp.conventional[condition]
      : productsByConditionAndFollowUp.pointOfCare[condition]

    if (!examData) return null

    const followUpTypes: FollowUpType[] = ['annual', 'semiannual', 'none']

    return (followUpTypes.map((followUpType) =>
      renderProductsTable(condition, followUpType, examData[followUpType], key)
    ))
  }

  // Verificar se TODAS as condições ativas estão 100% sem acompanhamento
  const hasNoFollowUp = useMemo(() => {
    const active = activeConditions
    if (active.length === 0) return false
    for (const disease of active) {
      const distribution = followUp[disease as keyof typeof followUp]
      if (distribution.none < 100) return false
    }
    return true
  }, [followUp, activeConditions])

  const scrollbarConfig = {
    minimalThumbYSize: 40,
    maximalThumbYSize: 40,
    disableTrackYWidthCompensation: true,
    className: 'space-y-2 h-full w-full',
    thumbYProps: {
      renderer: (props: ScrollbarElementProps) => {
        const { elementRef, ...restProps } = props
        return (
          <div
            {...restProps}
            ref={elementRef}
            style={{
              ...restProps.style,
              width: '40px',
              height: '40px',
              minWidth: '40px',
              minHeight: '40px',
              maxWidth: '40px',
              maxHeight: '40px',
              backgroundImage: 'url(ui/thumb2.svg)',
              backgroundSize: '40px 40px',
              backgroundRepeat: 'no-repeat',
              backgroundPosition: 'center',
              backgroundColor: '',
              border: '0.5px solid rgba(255, 255, 255, 0.2)',
              borderRadius: '50%',
              overflow: 'visible',
              display: 'flex',
              justifyContent: 'center',
              position: 'relative',
              left: '-14px',
              zIndex: 10
            }} />
        )
      }
    },
    trackYProps: {
      renderer: (props: ScrollbarElementProps) => {
        const { elementRef, ...restProps } = props
        return (
          <div
            {...restProps}
            ref={elementRef}
            style={{
              ...restProps.style,
              width: '14px',
              borderRadius: '100px',
              height: '97.5%',
              marginTop: '-5.5px',
              marginRight: '16.5px',
              overflow: 'visible',
              backgroundColor: 'rgba(0, 0, 0, 0.15)',
              border: '1px solid rgba(255, 255, 255, 0.1)'
            }} />
        )
      }
    }
  }

  // Botão + Scrollbar reutilizável (estilo herdado de PatientStep4)
  const renderExamProductsButton = (type: ExamType) => {
    const isSelected = examType === type
    return (
      <button
        type="button"
        className={`
          w-full cursor-pointer m-0.5 rounded-4xl transition-colors relative
          ${isSelected ? 'border-[#52AE32] ring-2 ring-[#52AE32]' : 'border-white/20 hover:border-white/30'}
        `}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault()
            updateExamType(type)
          }
        }}
        onClick={() => updateExamType(type)}>
        <div className="glass-container h-[calc(min(100dvh,950px)-22.5rem)] min-h-50">
          {!isSelected && (<div className="glass-filter"></div>)}
          <div className="glass-overlay"></div>
          <div className="glass-specular"></div>
          <div className="glass-content p-0! py-5! h-full justify-start!">
            <Scrollbar
              {...scrollbarConfig}
              onScroll={(e) => handleScroll(e, type)}
              style={{ height: '100%', width: '100%' }}>
              <div className="flex flex-col justify-between gap-10 pl-6 pr-12">
                {activeConditions.map((condition) => (
                  renderConditionTables(condition, type, `${type}-${condition}`)
                ))}
              </div>
            </Scrollbar>
          </div>
        </div>
      </button>
    )
  }

  return (
    <div className="mt-5.5 mb-6 w-full">
      {hasNoFollowUp && (
        <div className="flex items-center justify-center my-20">
          <div className="glass-container rounded-2xl max-w-200">
            <div className="glass-filter"></div>
            <div className="glass-overlay"></div>
            <div className="glass-specular"></div>
            <div className="glass-content">
              <div className="flex flex-col items-center gap-10 py-5">
                <div className="flex flex-col items-center justify-center gap-1">
                  <img src="ui/icon-warning.png" alt="Warning Sign" className="w-12 text-red-400" />
                  <h3 className="text-sm font-thin text-[#FFF15C]">
                    {t('noFollowUp.title')}
                  </h3>
                </div>
                <div className="flex items-center justify-center gap-1">
                  <img src="ui/icon-carbon.png" alt="Carbon Icon" className="h-16" />
                  <p className="mt-1 text-xs text-center max-w-50">
                    {t('noFollowUp.body')}
                  </p>
                  <img src="ui/icon-hospital.png" alt="Hospital Icon" className="h-14" />
                </div>
                <div className="flex items-center justify-center gap-1">
                  <p className="mt-1 text-sm text-center">
                    {t('noFollowUp.footer')}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {!hasNoFollowUp && (
        <>
          {/* Cabeçalho visível novamente também no mobile para manter referência vertical do popover */}
          <div>
            <SectionHeader
              title={t('step3.population.productsServicesTitle')}
              subtitle=" "
              className="absolute mt-4.5" />
          </div>

          {/* Seletor de tipo de exame + Popover (restaurado sem wrapper hidden para posição original) */}
          <div className="flex justify-center w-full gap-4 mb-4 select-none">
            {renderExamTypeButton('conventional', '/ui/icon-conventional.png', 'right')}
            {renderExamTypeButton('pointOfCare', '/ui/icon-pointofcare.png', 'left')}
            <AjudinhaPopover
              defaultOpen={true}
              hideTrigger={true}
              triggerClassName="absolute"
              side="right"
              align="end"
              contentClassName="w-full max-w-[200px] mt-22.5 rounded-4xl border-2 border-[#EE00FF] bg-[#01244CBA] shadow-lg"
              contentText={(
                <>
                  <img
                    src="ui/icon-hand-up.png"
                    alt="Purple Hand Up"
                    className="absolute -bottom-4 -left-14.5 w-17 -rotate-50" />
                  <div className="flex flex-col gap-0 text-center font-light text-[15px] text-[#E0E0E0]">
                    <p className="text-light text-[12px]">
                      {t('step3.population.selectMethodHint')}
                    </p>
                  </div>
                </>
              )} />
          </div>

          {/* Layout Mobile: só o tipo selecionado */}
          <div className="w-full lg:hidden">
            {examType === 'conventional' && renderExamProductsButton('conventional')}
            {examType === 'pointOfCare' && renderExamProductsButton('pointOfCare')}
          </div>

          {/* Layout Desktop: ambos lado a lado */}
          <div className="hidden w-full h-full gap-4 lg:flex lg:flex-row">
            {renderExamProductsButton('conventional')}
            {renderExamProductsButton('pointOfCare')}
          </div>
        </>
      )}
    </div>
  )
}
