import type { AutoGeneratedProduct, PatientConditions, PatientResults, PatientTransportation } from '@/types/patient'
import type { ExamType, FollowUpType } from '@/types/shared'
import { FREQUENCY_MULTIPLIERS } from '@/constants/emissions'
import { getSuggestionsByScenario } from '@/data/patientSuggestions'
import { calculateEmissionsByCondition, calculateProductEmissionsSum } from '@/utils/emissionsHelpers'
import { calculateTransportationEmissions } from '@/utils/transportationEmissions'

type ProductsByFollowUp = Record<FollowUpType, Record<ExamType, AutoGeneratedProduct[]>>

export function createConditionsRecord(conditions: PatientConditions): Record<string, boolean> {
  return {
    lowerBackPain: conditions.lowerBackPain,
    hypertension: conditions.hypertension,
    diabetes: conditions.diabetes,
    overweight: conditions.overweight,
    noChronicConditions: conditions.noChronicConditions
  }
}

export function generateRecommendations(
  examType: ExamType,
  followUpType: FollowUpType,
  conventionalEmissions: number,
  pointOfCareEmissions: number,
  withFollowUpEmissions: number,
  withoutFollowUpEmissions: number
): string[] {
  const recommendations = []
  const pocReduction = conventionalEmissions > 0
    ? ((conventionalEmissions - pointOfCareEmissions) / conventionalEmissions * 100).toFixed(0)
    : '0'

  if (examType === 'conventional' && pointOfCareEmissions < conventionalEmissions) {
    recommendations.push(`Considere migrar para exames Point of Care para reduzir ${pocReduction}% das emissões`)
  }
  if (followUpType === 'none') {
    const followUpReduction = ((withoutFollowUpEmissions - withFollowUpEmissions) / withoutFollowUpEmissions * 100).toFixed(0)
    recommendations.push(`Iniciar acompanhamento médico pode reduzir até ${followUpReduction}% das emissões`)
  }
  if (followUpType === 'annual') {
    recommendations.push('Acompanhamento semestral pode prevenir complicações e reduzir emissões')
  }

  return recommendations
}

export function calculateFullResults(
  allProductsByFollowUp: ProductsByFollowUp,
  currentFollowUp: FollowUpType,
  currentExamType: ExamType,
  conditions: PatientConditions,
  transportation: PatientTransportation,
  language: string = 'br'
): PatientResults {
  const frequencyMultiplier = FREQUENCY_MULTIPLIERS[currentFollowUp]
  const currentProducts = allProductsByFollowUp[currentFollowUp][currentExamType]

  const medicalEmissions = calculateProductEmissionsSum(currentProducts, frequencyMultiplier)
  const emissionsByDisease = calculateEmissionsByCondition(currentProducts, frequencyMultiplier)

  // Calcular emissões de transporte
  const transportationEmissions = calculateTransportationEmissions(
    transportation.type,
    transportation.distanceKm
  )

  const totalEmissions = medicalEmissions + transportationEmissions

  // Comparação Conventional vs Point of Care
  const conventionalProducts = allProductsByFollowUp[currentFollowUp].conventional
  const pointOfCareProducts = allProductsByFollowUp[currentFollowUp].pointOfCare
  const conventionalEmissions = calculateProductEmissionsSum(conventionalProducts, frequencyMultiplier)
  const pointOfCareEmissions = calculateProductEmissionsSum(pointOfCareProducts, frequencyMultiplier)

  // Comparação Com vs Sem Follow-up
  const withFollowUpProducts = allProductsByFollowUp[currentFollowUp][currentExamType]
  const withoutFollowUpProducts = allProductsByFollowUp.none[currentExamType]
  const withFollowUpEmissions = calculateProductEmissionsSum(withFollowUpProducts, frequencyMultiplier)
  const withoutFollowUpEmissions = calculateProductEmissionsSum(withoutFollowUpProducts, FREQUENCY_MULTIPLIERS.none)

  const avoidableEmissions = currentFollowUp === 'none'
    ? medicalEmissions
    : Math.max(0, withoutFollowUpEmissions - withFollowUpEmissions)

  const recommendations = generateRecommendations(
    currentExamType,
    currentFollowUp,
    conventionalEmissions,
    pointOfCareEmissions,
    withFollowUpEmissions,
    withoutFollowUpEmissions
  )

  const pocReductionPercent = conventionalEmissions > 0
    ? Math.round((conventionalEmissions - pointOfCareEmissions) / conventionalEmissions * 100)
    : 0

  const followUpReductionPercent = withoutFollowUpEmissions > 0
    ? Math.round((withoutFollowUpEmissions - withFollowUpEmissions) / withoutFollowUpEmissions * 100)
    : 0

  const suggestions = getSuggestionsByScenario(
    currentExamType,
    currentFollowUp,
    pocReductionPercent,
    followUpReductionPercent,
    conditions,
    language
  )

  return {
    totalEmissions,
    transportationEmissions,
    medicalEmissions,
    avoidableEmissions,
    conventionalVsPointOfCare: {
      conventional: conventionalEmissions,
      pointOfCare: pointOfCareEmissions
    },
    withVsWithoutFollowUp: {
      with: withFollowUpEmissions,
      without: withoutFollowUpEmissions
    },
    recommendations,
    suggestions,
    emissionsByDisease
  }
}
