import type { AutoGeneratedProduct } from '@/types/patient'
import type { FollowUpType } from '@/types/shared'

// Configuração de tipos de acompanhamento com multiplicador de frequência
export const followUpConfig: Record<FollowUpType, { text: string, frequencyMultiplier: number }> = {
  none: { text: 'Sem acompanhamento', frequencyMultiplier: 1 },
  annual: { text: 'Anual', frequencyMultiplier: 1 },
  semiannual: { text: 'Semestral', frequencyMultiplier: 2 }
}

// Labels das condições
export const conditionLabels: Record<string, string> = {
  lowerBackPain: 'Dor Lombar',
  hypertension: 'Hipertensão',
  diabetes: 'Diabetes',
  overweight: 'Sobrepeso/Obesidade',
  noChronicConditions: 'Sem Diagnóstico'
}

// Configuração de agrupamento - condições metabólicas são agrupadas
export const metabolicConditions = ['hypertension', 'diabetes', 'overweight']

export function isMetabolicCondition(condition: string): boolean {
  return metabolicConditions.includes(condition)
}

// Calcular emissões totais de um produto considerando o multiplicador de frequência
export function calculateTotalEmissions(product: AutoGeneratedProduct): number {
  const frequencyMultiplier = followUpConfig[product.followUpType as FollowUpType]?.frequencyMultiplier || 1
  return product.emissionFactor * product.quantity * frequencyMultiplier
}

// Calcular emissões totais de uma lista de produtos
export function calculateEmissionsForProducts(products: AutoGeneratedProduct[]): number {
  return products.reduce((total, product) => total + calculateTotalEmissions(product), 0)
}

// Obter o multiplicador de frequência de um follow-up
export function getFrequencyMultiplier(followUpType: FollowUpType): number {
  return followUpConfig[followUpType]?.frequencyMultiplier || 1
}

// Gerar label dinâmico para condições (incluindo agrupamento de condições metabólicas)
export function getConditionLabel(condition: string, selectedConditions: string[]): string {
  // Se for um grupo metabólico, criar label dinâmico
  if (condition === 'metabolic') {
    const selectedMetabolic = selectedConditions.filter(isMetabolicCondition)
    if (selectedMetabolic.length === 0) return 'Condições Metabólicas'
    if (selectedMetabolic.length === 1) return conditionLabels[selectedMetabolic[0]]

    const names = selectedMetabolic.map((c) => conditionLabels[c])
    if (names.length === 2) {
      return `${names[0]} e ${names[1]}`
    }
    const lastName = names[names.length - 1] // NOSONAR - Array.at() não disponível no target ES2020
    return `${names.slice(0, -1).join(', ')} e ${lastName}`
  }

  return conditionLabels[condition] || condition
}

// Determinar o grupo de uma condição
export function getConditionGroup(condition: string): string {
  return isMetabolicCondition(condition) ? 'metabolic' : condition
}
